Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2019-07, with the labels that each got.

#58 support ccn (Cloud Connect Network)
  CHANGELOG.md
  examples/tencentcloud-ccn/main.tf
  examples/tencentcloud-ccn/variables.tf
  go.mod
  go.sum
  tencentcloud/connectivity/client.go
  tencentcloud/connectivity/transport.go
  tencentcloud/data_source_tc_ccn_bandwidth_limits.go
  tencentcloud/data_source_tc_ccn_bandwidth_limits_test.go
  tencentcloud/data_source_tc_ccn_instances.go
  tencentcloud/data_source_tc_ccn_instances_test.go
  tencentcloud/data_source_tc_mysql_backup_list.go
  tencentcloud/extension_cnn.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_ccn.go
  tencentcloud/resource_tc_ccn_attachment.go
  tencentcloud/resource_tc_ccn_attachment_test.go
  tencentcloud/resource_tc_ccn_bandwidth_limit.go
  tencentcloud/resource_tc_ccn_bandwidth_limit_test.go
  tencentcloud/resource_tc_ccn_test.go
  tencentcloud/service_tencentcloud_ccn.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/client_profile.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/modules.txt
  website/docs/d/ccn_bandwidth_limits.html.markdown
  website/docs/d/ccn_instances.html.markdown
  website/docs/d/mysql_backup_list.html.markdown
  website/docs/r/ccn.html.markdown
  website/docs/r/ccn_attachment.html.markdown
  website/docs/r/ccn_bandwidth_limit.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#59 Upgrade terraform version to support GetSchema interface
  go.mod
Labels: size/XS

#63 fixed adding data_disks
  tencentcloud/data_source_tc_instance_types_test.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_instance_test.go
  tencentcloud/service_instance.go
Labels: size/M

#64 bugfixed on tencentcloud_instance and tencentcloud_eip_association
  CHANGELOG.md
  tencentcloud/resource_tc_eip_association.go
  tencentcloud/resource_tc_instance.go
  website/docs/r/eip_association.html.markdown
Labels: documentation, size/XS

#66 fixed security_group delete issue
  go.sum
  tencentcloud/resource_tc_security_group.go
Labels: size/XS

#69 checking eip bind status after binding #67
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_eip_association.go
  tencentcloud/service_tencentcloud_dc.go
Labels: size/S

#70 Delete mysql completely.
  CHANGELOG.md
  examples/tencentcloud-as/main.tf
  examples/tencentcloud-as/variables.tf
  examples/tencentcloud-cbs/main.tf
  examples/tencentcloud-cbs/variables.tf
  examples/tencentcloud-ccn/main.tf
  examples/tencentcloud-ccn/variables.tf
  examples/tencentcloud-container-cluster/variables.tf
  examples/tencentcloud-cos/main.tf
  examples/tencentcloud-cos/variables.tf
  examples/tencentcloud-dc/main.tf
  examples/tencentcloud-dc/variables.tf
  examples/tencentcloud-instance-reset/main.tf
  examples/tencentcloud-instance-simple/main.tf
  examples/tencentcloud-instance-vpc/main.tf
  examples/tencentcloud-instance/main.tf
  examples/tencentcloud-lb/main.tf
  examples/tencentcloud-mysql/main.tf
  examples/tencentcloud-mysql/variables.tf
  examples/tencentcloud-nat/main.tf
  examples/tencentcloud-security-group-rule/main.tf
  examples/tencentcloud-subnet/main.tf
  examples/tentcentcloud-redis/main.tf
  examples/tentcentcloud-redis/variables.tf
  go.mod
  go.sum
  tencentcloud/connectivity/client.go
  tencentcloud/resource_tc_mysql_instance.go
  tencentcloud/resource_tc_mysql_readonly_instance.go
  tencentcloud/service_tencentcloud_mysql.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/modules.txt
  website/docs/r/mysql_instance.html.markdown
  website/docs/r/mysql_readonly_instance.html.markdown
Labels: size/XXL

#72 Readonly mysql instance can't be released immediately.
  tencentcloud/extension_mysql.go
  tencentcloud/helper.go
  tencentcloud/resource_tc_mysql_instance.go
  tencentcloud/resource_tc_mysql_readonly_instance.go
  tencentcloud/service_tencentcloud_mysql.go
  website/docs/r/mysql_instance.html.markdown
  website/docs/r/mysql_readonly_instance.html.markdown
Labels: documentation, size/M

#76 support dcg ( direct connect gateway )
  CHANGELOG.md
  examples/tencentcloud-dcg/main.tf
  tencentcloud/data_source_tc_dc_gateway_ccn_routes.go
  tencentcloud/data_source_tc_dc_gateway_ccn_routes_test.go
  tencentcloud/data_source_tc_dc_gateway_instances.go
  tencentcloud/data_source_tc_dc_gateway_instances_test.go
  tencentcloud/extension_dc_gateway.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_dc_gateway.go
  tencentcloud/resource_tc_dc_gateway_ccn_route.go
  tencentcloud/resource_tc_dc_gateway_ccn_route_test.go
  tencentcloud/resource_tc_dc_gateway_test.go
  tencentcloud/resource_tc_dcx.go
  tencentcloud/service_tencentcloud_dcg.go
  website/docs/d/dc_gateway_ccn_routes.html.markdown
  website/docs/d/dc_gateway_instances.html.markdown
  website/docs/r/dc_gateway.html.markdown
  website/docs/r/dc_gateway_ccn_route.html.markdown
  website/docs/r/dcx.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XXL

#77 corrected vpc id reference in the route table
  examples/tencentcloud-subnet/main.tf
Labels: size/XS

#74 Rewrite security group related resource and data source
  CHANGELOG.md
  go.sum
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_security_group.go
  tencentcloud/data_source_tc_security_groups.go
  tencentcloud/data_source_tc_security_groups_test.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_security_group.go
  tencentcloud/resource_tc_security_group_rule.go
  tencentcloud/resource_tc_security_group_rule_test.go
  tencentcloud/resource_tc_security_group_test.go
  tencentcloud/service_tencentcloud_mysql.go
  tencentcloud/service_tencentcloud_vpc.go
  tencentcloud/validators.go
  website/docs/d/security_group.html.markdown
  website/docs/d/security_groups.html.markdown
  website/docs/r/security_group.html.markdown
  website/docs/r/security_group_rule.html.markdown
Labels: documentation, size/XXL

#80 support mongodb
  CHANGELOG.md
  examples/tencentcloud-mongodb/main.tf
  examples/tencentcloud-mongodb/variables.tf
  go.mod
  go.sum
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_mongodb_instances.go
  tencentcloud/data_source_tc_mongodb_instances_test.go
  tencentcloud/data_source_tc_mongodb_zone_config.go
  tencentcloud/data_source_tc_mongodb_zone_config_test.go
  tencentcloud/extension_mongodb.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_mongodb_instance.go
  tencentcloud/resource_tc_mongodb_instance_test.go
  tencentcloud/resource_tc_mongodb_sharding_instance.go
  tencentcloud/resource_tc_mongodb_sharding_instance_test.go
  tencentcloud/service_tencentcloud_mongodb.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/sign.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/mongodb/v20180408/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/mongodb/v20180408/models.go
  vendor/modules.txt
  website/docs/d/mongodb_instances.html.markdown
  website/docs/d/mongodb_zone_config.html.markdown
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL
