Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2019-12, with the labels that each got.

#217 fix CAM bugs
  tencentcloud/data_source_tc_cam_group_memberships.go
  tencentcloud/data_source_tc_cam_group_policy_attachments.go
  tencentcloud/data_source_tc_cam_groups.go
  tencentcloud/data_source_tc_cam_policies.go
  tencentcloud/data_source_tc_cam_role_policy_attachments.go
  tencentcloud/data_source_tc_cam_users.go
  tencentcloud/extension_cam.go
  tencentcloud/resource_tc_cam_user.go
  tencentcloud/service_tencentcloud_cam.go
  website/docs/d/cam_group_memberships.html.markdown
  website/docs/d/cam_group_policy_attachments.html.markdown
  website/docs/d/cam_groups.html.markdown
  website/docs/d/cam_policies.html.markdown
  website/docs/d/cam_role_policy_attachments.html.markdown
  website/docs/d/cam_user_policy_attachments.html.markdown
Labels: documentation, size/M

#221 optimize the format of sdk log
  tencentcloud/connectivity/transport.go
  website/docs/d/cam_group_policy_attachments.html.markdown
  website/docs/d/cam_user_policy_attachments.html.markdown
Labels: documentation, size/S

#225 add force new mark
  tencentcloud/resource_tc_cam_saml_provider.go
  website/docs/r/cam_saml_provider.html.markdown
Labels: documentation, size/XS

#227 fix type error
  tencentcloud/data_source_tc_nat_gateways.go
Labels: size/XS

#230 fix error test case
  tencentcloud/data_source_tc_nat_gateways_test.go
  tencentcloud/resource_tc_kubernetes_cluster.go
Labels: size/XS

#229 Update error message of validator
  tencentcloud/resource_tc_cbs_storage_attachment.go
  tencentcloud/validators.go
Labels: size/S

#232 Fix cvm instance type validator
  CHANGELOG.md
  tencentcloud/validators.go
Labels: size/XS

#220 New Resource: tencentcloud_kubernetes_as_scaling_group
  CHANGELOG.md
  examples/tencentcloud-tke/main.tf
  tencentcloud/provider.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_kubernetes_as_scaling_group.go
  tencentcloud/resource_tc_kubernetes_as_scaling_group_test.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/service_tencentcloud_tke.go
  website/docs/r/kubernetes_as_scaling_group.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XXL

#231 add new mysql resource tencentcloud_mysql_privilege
  CHANGELOG.md
  examples/tencentcloud-mysql/main.tf
  tencentcloud/extension_mysql.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_mysql_account_privilege.go
  tencentcloud/resource_tc_mysql_privilege.go
  tencentcloud/resource_tc_mysql_privilege_test.go
  website/docs/r/mysql_account_privilege.html.markdown
  website/docs/r/mysql_privilege.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XL

#234 add gaap import and new optional argument
  CHANGELOG.md
  examples/tencentcloud-gaap-layer7/main.tf
  go.mod
  go.sum
  tencentcloud/basic_test.go
  tencentcloud/data_source_tc_gaap_http_domains.go
  tencentcloud/data_source_tc_gaap_http_domains_test.go
  tencentcloud/data_source_tc_gaap_http_rules_test.go
  tencentcloud/data_source_tc_gaap_layer4_listeners.go
  tencentcloud/data_source_tc_gaap_layer4_listeners_test.go
  tencentcloud/data_source_tc_gaap_layer7_listeners.go
  tencentcloud/data_source_tc_gaap_layer7_listeners_test.go
  tencentcloud/data_source_tc_gaap_security_policies_test.go
  tencentcloud/data_source_tc_gaap_security_rules_test.go
  tencentcloud/extension_gaap.go
  tencentcloud/helper.go
  tencentcloud/resource_tc_gaap_http_domain.go
  tencentcloud/resource_tc_gaap_http_domain_test.go
  tencentcloud/resource_tc_gaap_http_rule.go
  tencentcloud/resource_tc_gaap_http_rule_test.go
  tencentcloud/resource_tc_gaap_layer4_listener.go
  tencentcloud/resource_tc_gaap_layer4_listener_test.go
  tencentcloud/resource_tc_gaap_layer7_listener.go
  tencentcloud/resource_tc_gaap_layer7_listener_test.go
  tencentcloud/resource_tc_gaap_security_policy.go
  tencentcloud/resource_tc_gaap_security_policy_test.go
  tencentcloud/resource_tc_gaap_security_rule.go
  tencentcloud/resource_tc_gaap_security_rule_test.go
  tencentcloud/service_tencentcloud_gaap.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
  vendor/modules.txt
  website/docs/d/gaap_http_domains.html.markdown
  website/docs/d/gaap_layer4_listeners.html.markdown
  website/docs/d/gaap_layer7_listeners.html.markdown
  website/docs/r/gaap_http_domain.html.markdown
  website/docs/r/gaap_http_rule.html.markdown
  website/docs/r/gaap_layer4_listener.html.markdown
  website/docs/r/gaap_layer7_listener.html.markdown
  website/docs/r/gaap_security_rule.html.markdown
Labels: dependencies, documentation, size/XXL

#236 fix CLB bugs
  tencentcloud/basic_test.go
  tencentcloud/data_source_tc_clb_attachments.go
  tencentcloud/data_source_tc_clb_instances.go
  tencentcloud/data_source_tc_clb_listener_rules.go
  tencentcloud/data_source_tc_clb_listeners.go
  tencentcloud/data_source_tc_clb_redirections.go
  tencentcloud/extension_clb.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_attachment_test.go
  tencentcloud/resource_tc_clb_instance.go
  tencentcloud/resource_tc_clb_instance_test.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  tencentcloud/resource_tc_clb_listener_rule_test.go
  tencentcloud/resource_tc_clb_listener_test.go
  tencentcloud/resource_tc_clb_redirection.go
  tencentcloud/resource_tc_clb_redirection_test.go
  tencentcloud/service_tencentcloud_clb.go
  website/docs/d/clb_attachments.html.markdown
  website/docs/d/clb_instances.html.markdown
  website/docs/d/clb_listeners.html.markdown
  website/docs/d/clb_redirections.html.markdown
  website/docs/r/clb_attachment.html.markdown
  website/docs/r/clb_listener.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
Labels: documentation, size/XL

#239 fixed docs
  tencentcloud/data_source_tc_dnats.go
  tencentcloud/resource_tc_cbs_snapshot_policy.go
  tencentcloud/resource_tc_dnat.go
  website/docs/d/dnats.html.markdown
  website/docs/r/cbs_snapshot_policy.html.markdown
  website/docs/r/dnat.html.markdown
Labels: documentation, size/S

#243 fix some issue
  CHANGELOG.md
  tencentcloud/data_source_tc_mongodb_instances.go
  tencentcloud/extension_cvm.go
  tencentcloud/resource_tc_as_attachment.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_mongodb_instance.go
  tencentcloud/resource_tc_mongodb_sharding_instance.go
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
Labels: documentation, size/M

#246 fix error of `assigned_eip_set` of resource `tencentcloud_nat_gateway`
  tencentcloud/resource_tc_nat_gateway.go
  website/docs/r/nat_gateway.html.markdown
Labels: documentation, size/XS

#247 Fix eip unattach
  CHANGELOG.md
  tencentcloud/data_source_tc_eip_test.go
  tencentcloud/extension_vpc.go
  tencentcloud/resource_tc_cbs_snapshot.go
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_eip_association.go
  tencentcloud/service_tencentcloud_vpc.go
Labels: size/M

#248 fix resource security_group read error
  CHANGELOG.md
  tencentcloud/common.go
  tencentcloud/service_tencentcloud_vpc.go
Labels: size/XS

#250 fix the bug that terraform read nil attachment resource when the attached resource has removed in resource CLB and CAM
  examples/tencentcloud-cam/variables.tf
  tencentcloud/data_source_tc_cam_group_memberships_test.go
  tencentcloud/data_source_tc_cam_policies.go
  tencentcloud/data_source_tc_clb_listener_rules.go
  tencentcloud/data_source_tc_clb_listeners.go
  tencentcloud/extension_ssl.go
  tencentcloud/resource_tc_cam_group.go
  tencentcloud/resource_tc_cam_group_membership.go
  tencentcloud/resource_tc_cam_group_membership_test.go
  tencentcloud/resource_tc_cam_group_policy_attachment_test.go
  tencentcloud/resource_tc_cam_group_test.go
  tencentcloud/resource_tc_cam_policy_test.go
  tencentcloud/resource_tc_cam_role_policy_attachment_test.go
  tencentcloud/resource_tc_cam_role_test.go
  tencentcloud/resource_tc_cam_saml_provider_test.go
  tencentcloud/resource_tc_cam_user.go
  tencentcloud/resource_tc_cam_user_policy_attachment_test.go
  tencentcloud/resource_tc_cam_user_test.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_attachment_test.go
  tencentcloud/resource_tc_clb_instance_test.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  tencentcloud/resource_tc_clb_listener_rule_test.go
  tencentcloud/resource_tc_clb_listener_test.go
  tencentcloud/resource_tc_clb_redirection.go
  tencentcloud/resource_tc_clb_redirection_test.go
  tencentcloud/resource_tc_nat_gateway.go
  tencentcloud/resource_tc_ssl_certificate.go
  tencentcloud/service_tencentcloud_cam.go
  tencentcloud/service_tencentcloud_clb.go
  tencentcloud/service_tencentcloud_ssl.go
  website/docs/r/nat_gateway.html.markdown
Labels: size/XL

#249 tcaplus supports.
  CHANGELOG.md
  examples/tencentcloud-tcaplus/main.tf
  examples/tencentcloud-tcaplus/variables.tf
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_tcaplus_applications.go
  tencentcloud/data_source_tc_tcaplus_applications_test.go
  tencentcloud/data_source_tc_tcaplus_idls.go
  tencentcloud/data_source_tc_tcaplus_idls_test.go
  tencentcloud/data_source_tc_tcaplus_tables.go
  tencentcloud/data_source_tc_tcaplus_tables_test.go
  tencentcloud/data_source_tc_tcaplus_zones.go
  tencentcloud/data_source_tc_tcaplus_zones_test.go
  tencentcloud/extension_tcaplus.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_tcaplus_application.go
  tencentcloud/resource_tc_tcaplus_application_test.go
  tencentcloud/resource_tc_tcaplus_idl.go
  tencentcloud/resource_tc_tcaplus_idl_test.go
  tencentcloud/resource_tc_tcaplus_table.go
  tencentcloud/resource_tc_tcaplus_table_test.go
  tencentcloud/resource_tc_tcaplus_zone.go
  tencentcloud/resource_tc_tcaplus_zone_test.go
  tencentcloud/service_tencentcloud_tcaplus.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcaplusdb/v20190823/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcaplusdb/v20190823/models.go
  vendor/modules.txt
  website/docs/d/tcaplus_applications.html.markdown
  website/docs/d/tcaplus_idls.html.markdown
  website/docs/d/tcaplus_tables.html.markdown
  website/docs/d/tcaplus_zones.html.markdown
  website/docs/r/tcaplus_application.html.markdown
  website/docs/r/tcaplus_idl.html.markdown
  website/docs/r/tcaplus_table.html.markdown
  website/docs/r/tcaplus_zone.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#256 idl not need `zone_id`
  tencentcloud/resource_tc_tcaplus_idl.go
  tencentcloud/resource_tc_tcaplus_table.go
  website/docs/r/tcaplus_idl.html.markdown
  website/docs/r/tcaplus_table.html.markdown
Labels: documentation, size/XS

#257 add additional error code to fix bugs
  tencentcloud/service_tencentcloud_cam.go
Labels: size/XS

#259 eip applicable_for_clb deprecated
  CHANGELOG.md
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_eip_test.go
  website/docs/r/eip.html.markdown
Labels: documentation, size/XS

#262 Adjust the order of tcaplus documents
  tencentcloud/provider.go
  website/tencentcloud.erb
Labels: documentation, size/S

#258 Support cbs snapshot policy attachment
  CHANGELOG.md
  tencentcloud/data_source_tc_cbs_snapshot_policys.go
  tencentcloud/data_source_tc_cbs_snapshot_policys_test.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_cbs_snapshot_policy_attachment.go
  tencentcloud/resource_tc_cbs_snapshot_policy_attachment_test.go
  tencentcloud/resource_tc_cbs_snapshot_policy_test.go
  tencentcloud/service_tencentcloud_cbs.go
  website/docs/d/cbs_snapshot_policys.html.markdown
  website/docs/r/cbs_snapshot_policy_attachment.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XL

#261 add gaap realserverCertificateIds support
  CHANGELOG.md
  examples/tencentcloud-gaap-certificate/main.tf
  examples/tencentcloud-gaap-layer4/main.tf
  examples/tencentcloud-gaap-layer7/main.tf
  examples/tencentcloud-gaap/main.tf
  go.mod
  go.sum
  tencentcloud/data_source_tc_gaap_http_domains.go
  tencentcloud/data_source_tc_gaap_http_domains_test.go
  tencentcloud/resource_tc_gaap_http_domain.go
  tencentcloud/resource_tc_gaap_http_domain_test.go
  tencentcloud/service_tencentcloud_gaap.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/github.com/vmihailenco/msgpack/.travis.yml
  vendor/github.com/vmihailenco/msgpack/CHANGELOG.md
  vendor/github.com/vmihailenco/msgpack/decode.go
  vendor/github.com/vmihailenco/msgpack/decode_map.go
  vendor/github.com/vmihailenco/msgpack/decode_query.go
  vendor/github.com/vmihailenco/msgpack/decode_slice.go
  vendor/github.com/vmihailenco/msgpack/decode_value.go
  vendor/github.com/vmihailenco/msgpack/encode.go
  vendor/github.com/vmihailenco/msgpack/encode_map.go
  vendor/github.com/vmihailenco/msgpack/encode_number.go
  vendor/github.com/vmihailenco/msgpack/encode_slice.go
  vendor/github.com/vmihailenco/msgpack/encode_value.go
  vendor/github.com/vmihailenco/msgpack/ext.go
  vendor/github.com/vmihailenco/msgpack/types.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/writesched_random.go
  vendor/modules.txt
  website/docs/d/gaap_http_domains.html.markdown
  website/docs/r/gaap_http_domain.html.markdown
Labels: dependencies, documentation, size/XXL

#266 rewrite website index
  CHANGELOG.md
  GNUmakefile
  gendoc/index.go
  gendoc/index_test.go
  gendoc/main.go
  gendoc/template.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_tcaplus_zone.go
  website/docs/r/tcaplus_zone.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XXL

#271 Increase waiting time of cvm and mysql
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_mysql_instance.go
Labels: size/XS

#273 FileContent urlencode +base64encode
  tencentcloud/service_tencentcloud_tcaplus.go
Labels: size/XS

#275 version limit.
  examples/tencentcloud-as/version.tf
  examples/tencentcloud-cam/version.tf
  examples/tencentcloud-cbs/version.tf
  examples/tencentcloud-ccn/version.tf
  examples/tencentcloud-cfs/version.tf
  examples/tencentcloud-clb/version.tf
  examples/tencentcloud-cos/version.tf
  examples/tencentcloud-dc/version.tf
  examples/tencentcloud-dcg/version.tf
  examples/tencentcloud-eip-association/version.tf
  examples/tencentcloud-eip/version.tf
  examples/tencentcloud-eni/version.tf
  examples/tencentcloud-gaap-certificate/version.tf
  examples/tencentcloud-gaap-layer4/version.tf
  examples/tencentcloud-gaap-layer7/version.tf
  examples/tencentcloud-gaap-security/version.tf
  examples/tencentcloud-gaap/version.tf
  examples/tencentcloud-havip/version.tf
  examples/tencentcloud-instance-reset/version.tf
  examples/tencentcloud-instance-security-groups/version.tf
  examples/tencentcloud-instance-simple/version.tf
  examples/tencentcloud-instance-vpc/version.tf
  examples/tencentcloud-instance/version.tf
  examples/tencentcloud-mongodb/version.tf
  examples/tencentcloud-mysql/version.tf
  examples/tencentcloud-nat/version.tf
  examples/tencentcloud-redis/version.tf
  examples/tencentcloud-route-table/version.tf
  examples/tencentcloud-scf/version.tf
  examples/tencentcloud-security-group-lite-rule/version.tf
  examples/tencentcloud-security-group-rule/version.tf
  examples/tencentcloud-security-group/version.tf
  examples/tencentcloud-ssl/version.tf
  examples/tencentcloud-subnet/version.tf
  examples/tencentcloud-tcaplus/version.tf
  examples/tencentcloud-tke/version.tf
  examples/tencentcloud-vpc/version.tf
  examples/tencentcloud-vpn/version.tf
Labels: size/M

#277 retry create tcaplus error code ResourceUnavailable
  tencentcloud/resource_tc_tcaplus_application.go
Labels: size/XS

#281 data source support default vpc & subnet
  CHANGELOG.md
  tencentcloud/data_source_tc_subnet.go
  tencentcloud/data_source_tc_vpc.go
  tencentcloud/data_source_tc_vpc_instances.go
  tencentcloud/data_source_tc_vpc_subnets.go
  tencentcloud/resource_tc_kubernetes_as_scaling_group_test.go
  tencentcloud/resource_tc_kubernetes_cluster_test.go
  tencentcloud/resource_tc_kubernetes_scale_worker_test.go
  tencentcloud/service_tencentcloud_vpc.go
  website/docs/d/vpc_instances.html.markdown
  website/docs/d/vpc_subnets.html.markdown
Labels: documentation, size/M

#284 Add format description of cos bucket
  tencentcloud/resource_tc_cos_bucket.go
  tencentcloud/resource_tc_cos_bucket_object.go
  website/docs/r/cos_bucket.html.markdown
  website/docs/r/cos_bucket_object.html.markdown
Labels: documentation, size/XS

#283 add new gaap resource and data source
  CHANGELOG.md
  examples/tencentcloud-gaap-layer7/main.tf
  gendoc/README.md
  tencentcloud/common.go
  tencentcloud/data_source_tc_gaap_domain_error_pages.go
  tencentcloud/data_source_tc_gaap_domain_error_pages_test.go
  tencentcloud/data_source_tc_gaap_security_rules.go
  tencentcloud/internal/helper/error.go
  tencentcloud/internal/helper/helper.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_gaap_domain_error_page.go
  tencentcloud/resource_tc_gaap_domain_error_page_test.go
  tencentcloud/resource_tc_gaap_http_domain.go
  tencentcloud/resource_tc_gaap_security_rule.go
  tencentcloud/resource_tc_security_group_rule.go
  tencentcloud/service_tencentcloud_gaap.go
  website/docs/d/gaap_domain_error_pages.html.markdown
  website/docs/r/gaap_domain_error_page.html.markdown
  website/docs/r/gaap_http_domain.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XXL
