Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2019-11, with the labels that each got.

#181 fix example error in the website
  CHANGELOG.md
  tencentcloud/resource_tc_cam_role_policy_attachment.go
  website/docs/r/cam_role_policy_attachment.html.markdown
Labels: documentation, size/XS

#187 update cvm data disk size limit
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_instance.go
  website/docs/r/cbs_storage.html.markdown
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#189 add tags support for eip
  CHANGELOG.md
  examples/tencentcloud-eip/main.tf
  tencentcloud/data_source_tc_eips.go
  tencentcloud/data_source_tc_eips_test.go
  tencentcloud/extension_vpc.go
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_eip_test.go
  website/docs/d/eips.html.markdown
  website/docs/r/eip.html.markdown
Labels: documentation, size/L

#183 add resrouce `vpn gateway`, `customer gateway` and `vpn connection`
  CHANGELOG.md
  examples/tencentcloud-vpn/main.tf
  examples/tencentcloud-vpn/variables.tf
  go.sum
  tencentcloud/data_source_tc_nat_gateways.go
  tencentcloud/data_source_tc_vpn_connections.go
  tencentcloud/data_source_tc_vpn_connections_test.go
  tencentcloud/data_source_tc_vpn_customer_gateways.go
  tencentcloud/data_source_tc_vpn_customer_gateways_test.go
  tencentcloud/data_source_tc_vpn_gateways.go
  tencentcloud/data_source_tc_vpn_gateways_test.go
  tencentcloud/extension_vpc.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_vpn_connection.go
  tencentcloud/resource_tc_vpn_connection_test.go
  tencentcloud/resource_tc_vpn_customer_gateway.go
  tencentcloud/resource_tc_vpn_customer_gateway_test.go
  tencentcloud/resource_tc_vpn_gateway.go
  tencentcloud/resource_tc_vpn_gateway_test.go
  tencentcloud/service_tencentcloud_vpc.go
  website/docs/d/vpn_connections.html.markdown
  website/docs/d/vpn_customer_gateways.html.markdown
  website/docs/d/vpn_gateways.html.markdown
  website/docs/r/nat_gateway.html.markdown
  website/docs/r/vpn_connection.html.markdown
  website/docs/r/vpn_customer_gateway.html.markdown
  website/docs/r/vpn_gateway.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XXL

#190 update eip association doc
  tencentcloud/resource_tc_eip_association.go
  website/docs/r/eip_association.html.markdown
Labels: documentation, size/XS

#191 fixed lint check
  tencentcloud/extension_vpc.go
  tencentcloud/resource_tc_vpn_connection.go
  website/docs/d/nat_gateways.html.markdown
  website/docs/r/nat_gateway.html.markdown
  website/docs/r/vpn_connection.html.markdown
Labels: documentation, size/XS

#196 fix large integer issue when building on 32-bit platform
  tencentcloud/resource_tc_vpn_connection.go
  website/docs/r/vpn_connection.html.markdown
Labels: documentation, size/XS

#197 Fix key pair destroy
  tencentcloud/extension_cvm.go
  tencentcloud/resource_tc_key_pair.go
Labels: size/XS

#198 Fix key pair destroy
  tencentcloud/resource_tc_key_pair.go
Labels: size/XS

#200 tencentcloud_kubernetes_cluster add new cluster_os
  CHANGELOG.md
  tencentcloud/data_source_tc_kubernetes_clusters.go
  tencentcloud/extension_tke.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/S

#201 add resouce `havip` and `havip eip attachment`.
  CHANGELOG.md
  examples/tencentcloud-havip/main.tf
  examples/tencentcloud-havip/variables.tf
  go.mod
  go.sum
  tencentcloud/connectivity/transport.go
  tencentcloud/data_source_tc_dnats.go
  tencentcloud/data_source_tc_eips.go
  tencentcloud/data_source_tc_ha_vip_eip_attachments.go
  tencentcloud/data_source_tc_ha_vip_eip_attachments_test.go
  tencentcloud/data_source_tc_ha_vips.go
  tencentcloud/data_source_tc_ha_vips_test.go
  tencentcloud/data_source_tc_nat_gateways.go
  tencentcloud/data_source_tc_vpn_connections.go
  tencentcloud/data_source_tc_vpn_customer_gateways.go
  tencentcloud/data_source_tc_vpn_gateways.go
  tencentcloud/extension_vpc.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_cam_user_policy_attachment.go
  tencentcloud/resource_tc_dnat.go
  tencentcloud/resource_tc_dnat_test.go
  tencentcloud/resource_tc_ha_vip.go
  tencentcloud/resource_tc_ha_vip_eip_attachment.go
  tencentcloud/resource_tc_ha_vip_eip_attachment_test.go
  tencentcloud/resource_tc_ha_vip_test.go
  tencentcloud/resource_tc_nat_gateway.go
  tencentcloud/resource_tc_vpn_gateway.go
  tencentcloud/service_tencentcloud_vpc.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cam/v20190116/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/modules.txt
  website/docs/d/dnats.html.markdown
  website/docs/d/ha_vip_eip_attachments.html.markdown
  website/docs/d/ha_vips.html.markdown
  website/docs/d/nat_gateways.html.markdown
  website/docs/d/vpn_customer_gateways.html.markdown
  website/docs/d/vpn_gateways.html.markdown
  website/docs/r/cam_user_policy_attachment.html.markdown
  website/docs/r/dnat.html.markdown
  website/docs/r/ha_vip.html.markdown
  website/docs/r/ha_vip_eip_attachment.html.markdown
  website/docs/r/nat_gateway.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#204 Feature/add tke instance charge type
  tencentcloud/extension_tke.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_cluster_test.go
  tencentcloud/resource_tc_kubernetes_scale_worker_test.go
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_scale_worker.html.markdown
Labels: documentation, size/M

#205 add default value and forceNew to instance charge_type and renew_flag
  CHANGELOG.md
  go.mod
  go.sum
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
  vendor/modules.txt
  website/docs/r/instance.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_scale_worker.html.markdown
Labels: dependencies, documentation, size/XL

#207 Cos tags
  CHANGELOG.md
  examples/tencentcloud-cos/main.tf
  tencentcloud/data_source_tc_cos_buckets.go
  tencentcloud/data_source_tc_cos_buckets_test.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_cos_bucket.go
  tencentcloud/resource_tc_cos_bucket_test.go
  tencentcloud/service_tencentcloud_cos.go
  website/docs/d/cos_buckets.html.markdown
  website/docs/r/cos_bucket.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XL

#211 change cbs snapshot wait timeout
  tencentcloud/connectivity/transport.go
  tencentcloud/resource_tc_cbs_snapshot.go
Labels: size/XS

#212 add SPOTPAID instance support #209
  CHANGELOG.md
  go.mod
  go.sum
  tencentcloud/extension_cvm.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_instance_test.go
  tencentcloud/validators.go
  vendor/github.com/athom/goset/.gitignore
  vendor/github.com/athom/goset/.travis.yml
  vendor/github.com/athom/goset/README.md
  vendor/github.com/athom/goset/helper.go
  vendor/github.com/athom/goset/set.go
  vendor/modules.txt
  website/docs/r/instance.html.markdown
Labels: dependencies, documentation, size/XL

#215 fixed cam example
  examples/tencentcloud-cam/variables.tf
  tencentcloud/resource_tc_cam_group_membership.go
  tencentcloud/resource_tc_cam_group_policy_attachment.go
  tencentcloud/resource_tc_cam_policy.go
  tencentcloud/resource_tc_cam_role.go
  tencentcloud/resource_tc_cam_role_policy_attachment.go
  tencentcloud/resource_tc_cam_user.go
  tencentcloud/resource_tc_cam_user_policy_attachment.go
  website/docs/r/cam_group_membership.html.markdown
  website/docs/r/cam_group_policy_attachment.html.markdown
  website/docs/r/cam_policy.html.markdown
  website/docs/r/cam_role.html.markdown
  website/docs/r/cam_role_policy_attachment.html.markdown
  website/docs/r/cam_user.html.markdown
  website/docs/r/cam_user_policy_attachment.html.markdown
Labels: documentation, size/L

#214 Auto remove cbs that has been deleted
  tencentcloud/resource_tc_cbs_snapshot.go
  tencentcloud/resource_tc_cbs_snapshot_policy.go
  tencentcloud/resource_tc_cbs_snapshot_policy_test.go
  tencentcloud/resource_tc_cbs_snapshot_test.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_cbs_storage_attachment.go
  tencentcloud/resource_tc_cbs_storage_attachment_test.go
  tencentcloud/resource_tc_cbs_storage_test.go
  tencentcloud/service_tencentcloud_cbs.go
Labels: size/L

#208 support prepaid VPN gateway
  CHANGELOG.md
  tencentcloud/data_source_tc_cam_group_memberships.go
  tencentcloud/data_source_tc_cam_group_memberships_test.go
  tencentcloud/data_source_tc_cam_group_policy_attachments.go
  tencentcloud/data_source_tc_cam_role_policy_attachments.go
  tencentcloud/data_source_tc_cam_user_policy_attachments.go
  tencentcloud/data_source_tc_cam_user_policy_attachments_test.go
  tencentcloud/data_source_tc_cam_users_test.go
  tencentcloud/extension_vpc.go
  tencentcloud/resource_tc_cam_group.go
  tencentcloud/resource_tc_cam_group_membership.go
  tencentcloud/resource_tc_cam_group_membership_test.go
  tencentcloud/resource_tc_cam_group_policy_attachment.go
  tencentcloud/resource_tc_cam_policy.go
  tencentcloud/resource_tc_cam_policy_test.go
  tencentcloud/resource_tc_cam_role.go
  tencentcloud/resource_tc_cam_role_policy_attachment.go
  tencentcloud/resource_tc_cam_saml_provider.go
  tencentcloud/resource_tc_cam_saml_provider_test.go
  tencentcloud/resource_tc_cam_user.go
  tencentcloud/resource_tc_cam_user_policy_attachment.go
  tencentcloud/resource_tc_cam_user_policy_attachment_test.go
  tencentcloud/resource_tc_cam_user_test.go
  tencentcloud/resource_tc_vpn_gateway.go
  tencentcloud/service_tencentcloud_cam.go
  website/docs/r/cam_role_policy_attachment.html.markdown
  website/docs/r/cam_user_policy_attachment.html.markdown
  website/docs/r/vpn_gateway.html.markdown
Labels: documentation, size/XL

#216 fixed cam example
  tencentcloud/data_source_tc_cam_group_memberships.go
  tencentcloud/data_source_tc_cam_group_policy_attachments.go
  tencentcloud/data_source_tc_cam_groups.go
  tencentcloud/data_source_tc_cam_policies.go
  tencentcloud/data_source_tc_cam_role_policy_attachments.go
  tencentcloud/data_source_tc_cam_roles.go
  tencentcloud/data_source_tc_cam_user_policy_attachments.go
  tencentcloud/data_source_tc_cam_users.go
  website/docs/d/cam_group_memberships.html.markdown
  website/docs/d/cam_group_policy_attachments.html.markdown
  website/docs/d/cam_groups.html.markdown
  website/docs/d/cam_policies.html.markdown
  website/docs/d/cam_role_policy_attachments.html.markdown
  website/docs/d/cam_roles.html.markdown
  website/docs/d/cam_user_policy_attachments.html.markdown
  website/docs/d/cam_users.html.markdown
Labels: documentation, size/L
