Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2019-10, with the labels that each got.

#156 add eni related resources
  examples/tencentcloud-eni/main.tf
  examples/tencentcloud-eni/variable.tf
  tencentcloud/data_source_tc_enis.go
  tencentcloud/data_source_tc_enis_test.go
  tencentcloud/extension_vpc.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_eni.go
  tencentcloud/resource_tc_eni_attachment.go
  tencentcloud/resource_tc_eni_attachment_test.go
  tencentcloud/resource_tc_eni_test.go
  tencentcloud/service_tencentcloud_vpc.go
  website/docs/d/enis.html.markdown
  website/docs/r/eni.html.markdown
  website/docs/r/eni_attachment.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XXL

#158 update eip & zones
  CHANGELOG.md
  tencentcloud/data_source_tc_availability_zones.go
  tencentcloud/extension_cvm.go
  tencentcloud/extension_vpc.go
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_eip_test.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/service_tencentcloud_cvm.go
  tencentcloud/service_tencentcloud_vpc.go
  website/docs/d/availability_zones.html.markdown
  website/docs/d/availability_zones.html.md
  website/docs/r/eip.html.markdown
  website/docs/r/instance.html.markdown
Labels: documentation, size/XL

#159 Fix gaap nil error
  CHANGELOG.md
  tencentcloud/data_source_tc_gaap_http_domains.go
  tencentcloud/resource_tc_gaap_http_domain.go
Labels: size/S

#162 As add waiting status
  tencentcloud/extension_as.go
  tencentcloud/resource_tc_as_notification.go
  tencentcloud/resource_tc_as_scaling_group.go
  tencentcloud/resource_tc_cos_bucket.go
  tencentcloud/resource_tc_instance.go
  website/docs/r/as_notification.html.markdown
Labels: documentation, size/S

#165 Fix type mismatch in sweepers
  tencentcloud/resource_tc_as_scaling_group_test.go
  tencentcloud/resource_tc_cos_bucket_test.go
Labels: size/XS

#161 Add retry to redis and as
  tencentcloud/extension_as.go
  tencentcloud/extension_redis.go
  tencentcloud/resource_tc_as_attachment.go
  tencentcloud/resource_tc_as_lifecycle_hook.go
  tencentcloud/resource_tc_as_lifecycle_hook_test.go
  tencentcloud/resource_tc_as_notification.go
  tencentcloud/resource_tc_as_scaling_config.go
  tencentcloud/resource_tc_as_scaling_config_test.go
  tencentcloud/resource_tc_as_scaling_group.go
  tencentcloud/resource_tc_as_scaling_group_test.go
  tencentcloud/resource_tc_as_scaling_policy.go
  tencentcloud/resource_tc_as_scaling_policy_test.go
  tencentcloud/resource_tc_as_schedule.go
  tencentcloud/resource_tc_ccn.go
  tencentcloud/resource_tc_ccn_attachment.go
  tencentcloud/resource_tc_ccn_bandwidth_limit.go
  tencentcloud/resource_tc_dc_gateway.go
  tencentcloud/resource_tc_dc_gateway_ccn_route.go
  tencentcloud/resource_tc_dcx.go
  tencentcloud/resource_tc_redis_backup_config.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/resource_tc_route_table.go
  tencentcloud/resource_tc_route_table_entry.go
  tencentcloud/resource_tc_security_group_rule.go
  tencentcloud/resource_tc_subnet.go
  tencentcloud/resource_tc_vpc.go
  tencentcloud/service_tencentcloud_as.go
Labels: size/XL

#164 Add more import support for gaap resources
  CHANGELOG.md
  tencentcloud/data_source_tc_gaap_layer7_listeners.go
  tencentcloud/resource_tc_gaap_http_domain.go
  tencentcloud/resource_tc_gaap_http_domain_test.go
  tencentcloud/resource_tc_gaap_layer7_listener.go
  tencentcloud/resource_tc_gaap_layer7_listener_test.go
  website/docs/r/gaap_http_domain.html.markdown
  website/docs/r/gaap_layer7_listener.html.markdown
Labels: documentation, size/XL

#168 fix sometimes can't enable realserver auth
  CHANGELOG.md
  tencentcloud/resource_tc_gaap_http_domain.go
Labels: size/XS

#169 support reserved instance
  CHANGELOG.md
  go.mod
  go.sum
  tencentcloud/data_source_tc_reserved_instance_configs.go
  tencentcloud/data_source_tc_reserved_instance_configs_test.go
  tencentcloud/data_source_tc_reserved_instances.go
  tencentcloud/data_source_tc_reserved_instances_test.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_reserved_instance.go
  tencentcloud/service_tencentcloud_cvm.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/http_profile.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/modules.txt
  website/docs/d/reserved_instance_configs.html.markdown
  website/docs/d/reserved_instances.html.markdown
  website/docs/r/reserved_instance.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#171 fix spelling issues and add erb file
  website/docs/d/cam_role_policy_attachments.html.markdown
  website/docs/d/cam_user_policy_attachments.html.markdown
  website/docs/r/as_scaling_config.html.markdown
  website/docs/r/cam_group.html.markdown
  website/docs/r/cam_group_membership.html.markdown
  website/docs/r/cam_group_policy_attachment.html.markdown
  website/docs/r/cam_role_policy_attachment.html.markdown
  website/docs/r/cam_user.html.markdown
  website/docs/r/cam_user_policy_attachment.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/M

#172 clean up after update to go1.3.x
  .go-version
  .travis.yml
  CHANGELOG.md
  README.md
  go.mod
  go.sum
Labels: size/S

#176 Add errors handling logic for tke
  CHANGELOG.md
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_scale_worker.go
Labels: size/S

#173 add tags support for tke related tags
  CHANGELOG.md
  examples/tencentcloud-tke/main.tf
  tencentcloud/data_source_tc_kubernetes_clusters.go
  tencentcloud/data_source_tc_kubernetes_clusters_test.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_cluster_test.go
  tencentcloud/resource_tc_kubernetes_scale_worker.go
  tencentcloud/resource_tc_kubernetes_scale_worker_test.go
  tencentcloud/service_tencentcloud_tke.go
  website/docs/d/kubernetes_clusters.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_scale_worker.html.markdown
Labels: documentation, size/XL

#177 modify cvm parameters for tke logic.
  tencentcloud/resource_tc_kubernetes_cluster.go
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_scale_worker.html.markdown
Labels: documentation, size/S

#180 Support cfs
  CHANGELOG.md
  examples/tencentcloud-cfs/main.tf
  examples/tencentcloud-cfs/variables.tf
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_cfs_access_groups.go
  tencentcloud/data_source_tc_cfs_access_groups_test.go
  tencentcloud/data_source_tc_cfs_access_rules.go
  tencentcloud/data_source_tc_cfs_access_rules_test.go
  tencentcloud/data_source_tc_cfs_file_systems.go
  tencentcloud/data_source_tc_cfs_file_systems_test.go
  tencentcloud/errors.go
  tencentcloud/extension_cfs.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_cfs_access_group.go
  tencentcloud/resource_tc_cfs_access_group_test.go
  tencentcloud/resource_tc_cfs_access_rule.go
  tencentcloud/resource_tc_cfs_access_rule_test.go
  tencentcloud/resource_tc_cfs_file_system.go
  tencentcloud/resource_tc_cfs_file_system_test.go
  tencentcloud/service_tencentcloud_cfs.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cfs/v20190719/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cfs/v20190719/models.go
  vendor/modules.txt
  website/docs/d/cfs_access_groups.html.markdown
  website/docs/d/cfs_access_rules.html.markdown
  website/docs/d/cfs_file_systems.html.markdown
  website/docs/r/cfs_access_group.html.markdown
  website/docs/r/cfs_access_rule.html.markdown
  website/docs/r/cfs_file_system.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#179 Add scf related resources
  CHANGELOG.md
  examples/tencentcloud-scf/main.tf
  examples/tencentcloud-scf/variable.tf
  go.mod
  tencentcloud/common.go
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_scf_functions.go
  tencentcloud/data_source_tc_scf_functions_test.go
  tencentcloud/data_source_tc_scf_logs.go
  tencentcloud/data_source_tc_scf_logs_test.go
  tencentcloud/data_source_tc_scf_namespaces.go
  tencentcloud/data_source_tc_scf_namespaces_test.go
  tencentcloud/extension_scf.go
  tencentcloud/helper.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_cos_bucket_object.go
  tencentcloud/resource_tc_scf_function.go
  tencentcloud/resource_tc_scf_function_test.go
  tencentcloud/resource_tc_scf_namespace.go
  tencentcloud/resource_tc_scf_namespace_test.go
  tencentcloud/service_tencentcloud_scf.go
  tencentcloud/service_tencentcloud_tag.go
  tencentcloud/validators.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/scf/v20180416/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/scf/v20180416/models.go
  vendor/modules.txt
  website/docs/d/scf_functions.html.markdown
  website/docs/d/scf_logs.html.markdown
  website/docs/d/scf_namespaces.html.markdown
  website/docs/r/scf_function.html.markdown
  website/docs/r/scf_namespace.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL
