Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2019-06, with the labels that each got.

#51 bug fix project_id
  CHANGELOG.md
  tencentcloud/data_source_tc_security_group.go
  tencentcloud/resource_tc_security_group.go
Labels: size/S

#53 fixed recreate instance with private ip #46
  CHANGELOG.md
  README.md
  tencentcloud/data_source_tc_instance_types_test.go
  tencentcloud/resource_tc_cos_bucket.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_instance_test.go
  website/docs/r/cos_bucket.html.markdown
Labels: documentation, size/L

#55 add github template
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Question.md
  .github/SUPPORT.md
Labels: size/L

#56 refactoring vpc logic with api3.0
  CHANGELOG.md
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_instance_types_test.go
  tencentcloud/data_source_tc_vpc_instances.go
  tencentcloud/data_source_tc_vpc_instances_test.go
  tencentcloud/data_source_tc_vpc_route_tables.go
  tencentcloud/data_source_tc_vpc_route_tables_test.go
  tencentcloud/data_source_tc_vpc_subnets.go
  tencentcloud/data_source_tc_vpc_subnets_test.go
  tencentcloud/errors.go
  tencentcloud/extension_vpc.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_cos_bucket.go
  tencentcloud/resource_tc_route_table.go
  tencentcloud/resource_tc_route_table_entry.go
  tencentcloud/resource_tc_route_table_entry_test.go
  tencentcloud/resource_tc_route_table_test.go
  tencentcloud/resource_tc_subnet.go
  tencentcloud/resource_tc_subnet_test.go
  tencentcloud/resource_tc_vpc.go
  tencentcloud/resource_tc_vpc_test.go
  tencentcloud/service_tencentcloud_vpc.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  website/docs/d/route_table.html.markdown
  website/docs/d/subnet.html.markdown
  website/docs/d/vpc.html.markdown
  website/docs/d/vpc_instances.html.markdown
  website/docs/d/vpc_route_tables.html.markdown
  website/docs/d/vpc_subnets.html.markdown
  website/docs/r/route_entry.html.markdown
  website/docs/r/route_table.html.markdown
  website/docs/r/route_table_entry.html.markdown
  website/docs/r/subnet.html.markdown
  website/docs/r/vpc.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#57 refactoring cbs logic with api3.0
  CHANGELOG.md
  examples/tencentcloud-cbs/main.tf
  examples/tencentcloud-cbs/variables.tf
  examples/tencentcloud-security-group-rule/main.tf
  examples/tencentcloud-snapshot/main.tf
  examples/tencentcloud-snapshot/variables.tf
  examples/tencentcloud-storage-attachment/main.tf
  examples/tencentcloud-storage-attachment/variables.tf
  examples/tencentcloud-storage/main.tf
  examples/tencentcloud-storage/variables.tf
  go.mod
  go.sum
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_cbs_snapshots.go
  tencentcloud/data_source_tc_cbs_snapshots_test.go
  tencentcloud/data_source_tc_cbs_storages.go
  tencentcloud/data_source_tc_cbs_storages_test.go
  tencentcloud/extension_cbs.go
  tencentcloud/helper.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_as_attachment.go
  tencentcloud/resource_tc_cbs_snapshot.go
  tencentcloud/resource_tc_cbs_snapshot_policy.go
  tencentcloud/resource_tc_cbs_snapshot_policy_test.go
  tencentcloud/resource_tc_cbs_snapshot_test.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_cbs_storage_attachment.go
  tencentcloud/resource_tc_cbs_storage_attachment_test.go
  tencentcloud/resource_tc_cbs_storage_test.go
  tencentcloud/resource_tc_cos_bucket.go
  tencentcloud/resource_tc_redis_backup_config.go
  tencentcloud/resource_tc_security_group_rule.go
  tencentcloud/resource_tc_security_group_rule_test.go
  tencentcloud/service_security_group.go
  tencentcloud/service_tencentcloud_cbs.go
  tencentcloud/service_tencentcloud_vpc.go
  tencentcloud/validators.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/modules.txt
  website/docs/d/cbs_snapshots.html.markdown
  website/docs/d/cbs_storages.html.markdown
  website/docs/r/as_attachment.html.markdown
  website/docs/r/as_notification.html.markdown
  website/docs/r/cbs_snapshot.html.markdown
  website/docs/r/cbs_snapshot_policy.html.markdown
  website/docs/r/cbs_storage.html.markdown
  website/docs/r/cbs_storage_attachment.html.markdown
  website/docs/r/cos_bucket.html.markdown
  website/docs/r/redis_backup_config.html.markdown
  website/docs/r/security_group_rule.html.markdown
  website/tencentcloud.erb
Labels: size/XXL
