Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2019-09, with the labels that each got.

#125 Use static proxy id in unit test
  tencentcloud/data_source_tc_gaap_http_domains_test.go
  tencentcloud/data_source_tc_gaap_http_rules_test.go
  tencentcloud/data_source_tc_gaap_layer4_listeners_test.go
  tencentcloud/data_source_tc_gaap_layer7_listeners_test.go
  tencentcloud/data_source_tc_gaap_security_policies_test.go
  tencentcloud/data_source_tc_gaap_security_rules_test.go
  tencentcloud/extension_gaap.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_gaap_http_domain_test.go
  tencentcloud/resource_tc_gaap_http_rule_test.go
  tencentcloud/resource_tc_gaap_layer4_listener_test.go
  tencentcloud/resource_tc_gaap_layer7_listener_test.go
  tencentcloud/resource_tc_gaap_security_policy_test.go
  tencentcloud/resource_tc_gaap_security_rule_test.go
  tencentcloud/service_tencentcloud_gaap.go
  website/tencentcloud.erb
Labels: documentation, size/XL

#126 add auto redirection in resouce redirection
  tencentcloud/extension_clb.go
  tencentcloud/resource_tc_clb_redirection.go
  tencentcloud/resource_tc_clb_redirection_test.go
  website/docs/d/clb_redirections.html.markdown
  website/docs/r/clb_redirection.html.markdown
Labels: documentation, size/XL

#127 Add ssl related resources
  CHANGELOG.md
  examples/tencentcloud-ssl/main.tf
  examples/tencentcloud-ssl/variable.tf
  go.mod
  go.sum
  tencentcloud/common.go
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_ssl_certificates.go
  tencentcloud/data_source_tc_ssl_certificates_test.go
  tencentcloud/extension_ssl.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_ssl_certificate.go
  tencentcloud/resource_tc_ssl_certificate_test.go
  tencentcloud/service_tencencloud_ssl.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/wss/v20180426/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/wss/v20180426/models.go
  vendor/modules.txt
  website/docs/d/ssl_certificates.html.markdown
  website/docs/r/ssl_certificate.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#128 Nat dev
  CHANGELOG.md
  tencentcloud/data_source_tc_dnats.go
  tencentcloud/data_source_tc_dnats_test.go
  tencentcloud/data_source_tc_nat_gateways.go
  tencentcloud/data_source_tc_nat_gateways_test.go
  tencentcloud/data_source_tc_nats.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_dnat.go
  tencentcloud/resource_tc_dnat_test.go
  tencentcloud/resource_tc_nat_gateway.go
  tencentcloud/resource_tc_nat_gateway_test.go
  website/docs/d/dnats.html.markdown
  website/docs/d/nat_gateways.html.markdown
  website/docs/r/dnat.html.markdown
  website/docs/r/nat_gateway.html.markdown
Labels: documentation, size/XXL

#129 Tentcent kubernetes Engine supports pull out authentication information.
  CHANGELOG.md
  tencentcloud/data_source_tc_kubernetes_clusters.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_cluster_test.go
  tencentcloud/resource_tc_kubernetes_scale_worker.go
  tencentcloud/service_tencencloud_tke.go
  website/docs/d/kubernetes_clusters.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/XL

#131 bug fix:when the mysql is abnormal state, read the basic information report error
  CHANGELOG.md
  tencentcloud/extension_mysql.go
  tencentcloud/resource_tc_mysql_instance.go
Labels: size/XS

#130 Add tags support for vpc, subnet, route table
  CHANGELOG.md
  examples/tencentcloud-route-table/main.tf
  examples/tencentcloud-vpc/main.tf
  go.mod
  go.sum
  tencentcloud/data_source_tc_vpc_instances.go
  tencentcloud/data_source_tc_vpc_instances_test.go
  tencentcloud/data_source_tc_vpc_route_tables.go
  tencentcloud/data_source_tc_vpc_route_tables_test.go
  tencentcloud/data_source_tc_vpc_subnets.go
  tencentcloud/data_source_tc_vpc_subnets_test.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_route_table.go
  tencentcloud/resource_tc_route_table_test.go
  tencentcloud/resource_tc_subnet.go
  tencentcloud/resource_tc_subnet_test.go
  tencentcloud/resource_tc_vpc.go
  tencentcloud/resource_tc_vpc_test.go
  tencentcloud/service_tencentcloud_tag.go
  tencentcloud/service_tencentcloud_vpc.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/models.go
  vendor/modules.txt
  website/docs/d/vpc_instances.html.markdown
  website/docs/d/vpc_route_tables.html.markdown
  website/docs/d/vpc_subnets.html.markdown
  website/docs/r/route_table.html.markdown
  website/docs/r/subnet.html.markdown
  website/docs/r/vpc.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#132 bug fix :after delete redis, the instance info is nil
  tencentcloud/connectivity/client.go
  tencentcloud/resource_tc_redis_instance_test.go
Labels: size/XS

#135 fix unclear description and error in example
  CHANGELOG.md
  tencentcloud/data_source_tc_clb_listener_rules.go
  tencentcloud/resource_tc_clb_listener_rule.go
  website/docs/d/clb_listener_rules.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
Labels: documentation, size/XS

#134 Add resource security_group_lite_rule
  CHANGELOG.md
  examples/tencentcloud-security-group-lite-rule/main.tf
  go.mod
  go.sum
  tencentcloud/data_source_tc_security_groups.go
  tencentcloud/data_source_tc_security_groups_test.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_security_group_lite_rule.go
  tencentcloud/resource_tc_security_group_lite_rule_test.go
  tencentcloud/service_tencentcloud_vpc.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
  vendor/modules.txt
  website/docs/d/security_groups.html.markdown
  website/docs/r/security_group_lite_rule.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#140 Fix cvm hostname is not work
  CHANGELOG.md
  tencentcloud/resource_tc_instance.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#139 Add resource security_group, data source security_groups tags support
  CHANGELOG.md
  examples/tencentcloud-security-group/main.tf
  tencentcloud/common.go
  tencentcloud/data_source_tc_security_groups.go
  tencentcloud/data_source_tc_security_groups_test.go
  tencentcloud/extension_security_group.go
  tencentcloud/extension_tags.go
  tencentcloud/resource_tc_security_group.go
  tencentcloud/resource_tc_security_group_test.go
  tencentcloud/service_tencentcloud_tag.go
  tencentcloud/service_tencentcloud_vpc.go
  website/docs/d/security_groups.html.markdown
  website/docs/r/security_group.html.markdown
Labels: documentation, size/XL

#141 update verification rule of as internet charge type
  CHANGELOG.md
  tencentcloud/extension_as.go
  tencentcloud/resource_tc_as_scaling_config.go
  website/docs/r/as_scaling_config.html.markdown
Labels: documentation, size/XS

#144 Miss argument availability_zone causes mysql recreated
  CHANGELOG.md
  tencentcloud/resource_tc_mysql_instance.go
Labels: size/XS

#143 Add mongodb tags support
  CHANGELOG.md
  examples/tencentcloud-mongodb/main.tf
  tencentcloud/data_source_tc_mongodb_instances.go
  tencentcloud/data_source_tc_mongodb_instances_test.go
  tencentcloud/resource_tc_mongodb_instance.go
  tencentcloud/resource_tc_mongodb_instance_test.go
  tencentcloud/resource_tc_mongodb_sharding_instance.go
  tencentcloud/resource_tc_mongodb_sharding_instance_test.go
  website/docs/d/mongodb_instances.html.markdown
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
Labels: documentation, size/XL

#142 Add tags support for redis_instance
  CHANGELOG.md
  examples/tencentcloud-redis/main.tf
  tencentcloud/data_source_tc_redis_instances.go
  tencentcloud/data_source_tc_redis_instances_test.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/resource_tc_redis_instance_test.go
  tencentcloud/service_tencentcloud_redis.go
  tencentcloud/service_tencentcloud_tag.go
  website/docs/d/redis_instances.html.markdown
  website/docs/r/redis_instance.html.markdown
Labels: documentation, size/XL

#146 Add retry logic into mysql
  tencentcloud/resource_tc_mysql_account.go
  tencentcloud/resource_tc_mysql_account_privilege.go
  tencentcloud/resource_tc_mysql_backup_policy.go
  tencentcloud/resource_tc_mysql_instance.go
  tencentcloud/resource_tc_mysql_readonly_instance.go
Labels: size/XL

#149 check Chinese symbol in description
  gendoc/main.go
  tencentcloud/data_source_tc_dnats.go
  tencentcloud/data_source_tc_nat_gateways.go
  tencentcloud/resource_tc_dc_gateway.go
  tencentcloud/resource_tc_dnat.go
  tencentcloud/resource_tc_mysql_instance.go
  tencentcloud/resource_tc_nat_gateway.go
  website/docs/d/dnats.html.markdown
  website/docs/d/nat_gateways.html.markdown
  website/docs/r/cos_bucket.html.markdown
  website/docs/r/dc_gateway.html.markdown
  website/docs/r/dnat.html.markdown
  website/docs/r/mysql_instance.html.markdown
  website/docs/r/mysql_readonly_instance.html.markdown
  website/docs/r/nat_gateway.html.markdown
Labels: documentation, size/S

#148 update key_pair & eip & placment_group
  CHANGELOG.md
  examples/tencentcloud-instance/main.tf
  tencentcloud/data_source_tc_eip.go
  tencentcloud/data_source_tc_eip_test.go
  tencentcloud/data_source_tc_eips.go
  tencentcloud/data_source_tc_eips_test.go
  tencentcloud/data_source_tc_instance_types.go
  tencentcloud/data_source_tc_instance_types_test.go
  tencentcloud/data_source_tc_instances.go
  tencentcloud/data_source_tc_instances_test.go
  tencentcloud/data_source_tc_key_pairs.go
  tencentcloud/data_source_tc_key_pairs_test.go
  tencentcloud/data_source_tc_placement_groups.go
  tencentcloud/data_source_tc_placement_groups_test.go
  tencentcloud/extension_cvm.go
  tencentcloud/extension_vpc.go
  tencentcloud/helper.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_eip_association.go
  tencentcloud/resource_tc_eip_association_test.go
  tencentcloud/resource_tc_eip_test.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_instance_test.go
  tencentcloud/resource_tc_key_pair.go
  tencentcloud/resource_tc_key_pair_test.go
  tencentcloud/resource_tc_placement_group.go
  tencentcloud/resource_tc_placement_group_test.go
  tencentcloud/service_eip.go
  tencentcloud/service_instance.go
  tencentcloud/service_key_pair.go
  tencentcloud/service_tencentcloud_cvm.go
  tencentcloud/service_tencentcloud_vpc.go
  website/docs/d/eip.html.markdown
  website/docs/d/eips.html.markdown
  website/docs/d/instance_types.html.markdown
  website/docs/d/instances.html.markdown
  website/docs/d/key_pairs.html.markdown
  website/docs/d/placement_groups.html.markdown
  website/docs/r/eip.html.markdown
  website/docs/r/eip_association.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/key_pair.html.markdown
  website/docs/r/placement_group.html.markdown
  website/tencentcloud.erb
Labels: size/XXL

#150 add git hooks
  .githooks/pre-commit
  GNUmakefile
  website/docs/r/cos_bucket.html.markdown
Labels: documentation, size/S

#151 Add forward_host for gaap_http_rule
  CHANGELOG.md
  examples/tencentcloud-gaap-layer7/main.tf
  tencentcloud/data_source_tc_gaap_http_rules.go
  tencentcloud/data_source_tc_gaap_http_rules_test.go
  tencentcloud/resource_tc_gaap_http_rule.go
  tencentcloud/resource_tc_gaap_http_rule_test.go
  tencentcloud/service_tencentcloud_gaap.go
  website/docs/d/gaap_http_rules.html.markdown
  website/docs/r/gaap_http_rule.html.markdown
Labels: documentation, size/XL

#152 sort and uniq sub struct when generate doc
  gendoc/main.go
  website/docs/r/cos_bucket.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_scale_worker.html.markdown
Labels: documentation, size/M

#153 fixed check equal
  .githooks/pre-commit
Labels: size/XS

#154 add check ContainsBigSymbol
  gendoc/gendoc_test.go
  gendoc/main.go
  tencentcloud/data_source_tc_mysql_instance.go
  tencentcloud/resource_tc_mysql_instance.go
  website/docs/d/mysql_instance.html.markdown
  website/docs/r/mysql_instance.html.markdown
  website/docs/r/mysql_readonly_instance.html.markdown
Labels: documentation, size/S

#157 Add as scaling group tags support
  CHANGELOG.md
  examples/tencentcloud-as/main.tf
  tencentcloud/data_source_tc_as_scaling_groups.go
  tencentcloud/data_source_tc_as_scaling_groups_test.go
  tencentcloud/resource_tc_as_scaling_group.go
  tencentcloud/resource_tc_as_scaling_group_test.go
  tencentcloud/service_tencentcloud_as.go
  website/docs/d/as_scaling_groups.html.markdown
  website/docs/r/as_scaling_group.html.markdown
Labels: documentation, size/XL
