Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2019-08, with the labels that each got.

#84 update mongodb doc
  tencentcloud/data_source_tc_mongodb_instances.go
  tencentcloud/data_source_tc_mongodb_zone_config.go
  website/docs/d/mongodb_instances.html.markdown
  website/docs/d/mongodb_zone_config.html.markdown
Labels: documentation, size/S

#83 add retry on api
  tencentcloud/data_source_tc_cbs_snapshots.go
  tencentcloud/data_source_tc_cbs_storages.go
  tencentcloud/data_source_tc_security_groups.go
  tencentcloud/resource_tc_cbs_snapshot.go
  tencentcloud/resource_tc_cbs_snapshot_policy.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_cbs_storage_attachment.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_security_group.go
  tencentcloud/resource_tc_security_group_rule.go
  website/docs/d/cbs_snapshots.html.markdown
  website/docs/r/cbs_snapshot.html.markdown
  website/docs/r/cbs_snapshot_policy.html.markdown
  website/docs/r/cbs_storage.html.markdown
Labels: size/L

#85 Fix security_group_rule buildID
  tencentcloud/resource_tc_security_group_rule.go
  tencentcloud/resource_tc_security_group_rule_test.go
  tencentcloud/service_tencentcloud_vpc.go
Labels: size/M

#86 Fix rule
  tencentcloud/service_tencentcloud_vpc.go
Labels: size/S

#87 auto format example in docs
  examples/tencentcloud-instance/main.tf
  examples/tencentcloud-route-entry/main.tf
  gendoc/gendoc_test.go
  gendoc/main.go
  go.mod
  tencentcloud/data_source_tc_ccn_bandwidth_limits.go
  tencentcloud/data_source_tc_dc_instances.go
  tencentcloud/data_source_tc_dcx_instances.go
  tencentcloud/data_source_tc_security_group.go
  tencentcloud/data_source_tc_security_groups.go
  tencentcloud/data_source_tc_vpc_route_tables.go
  tencentcloud/data_source_tc_vpc_subnets.go
  tencentcloud/resource_tc_as_scaling_config.go
  tencentcloud/resource_tc_ccn_bandwidth_limit.go
  tencentcloud/resource_tc_cos_bucket.go
  tencentcloud/resource_tc_dcx.go
  tencentcloud/resource_tc_security_group_rule.go
  tencentcloud/resource_tc_subnet.go
  website/docs/d/cbs_snapshots.html.markdown
  website/docs/d/dc_gateway_ccn_routes.html.markdown
  website/docs/d/dc_gateway_instances.html.markdown
  website/docs/d/mysql_backup_list.html.markdown
  website/docs/d/mysql_instance.html.markdown
  website/docs/d/mysql_parameter_list.html.markdown
  website/docs/d/mysql_zone_config.html.markdown
  website/docs/d/security_group.html.markdown
  website/docs/d/security_groups.html.markdown
  website/docs/r/cbs_snapshot.html.markdown
  website/docs/r/cbs_snapshot_policy.html.markdown
  website/docs/r/cos_bucket.html.markdown
  website/docs/r/dc_gateway.html.markdown
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
  website/docs/r/mysql_account.html.markdown
  website/docs/r/mysql_account_privilege.html.markdown
  website/docs/r/mysql_backup_policy.html.markdown
  website/docs/r/security_group.html.markdown
  website/docs/r/security_group_rule.html.markdown
Labels: documentation, size/L

#73 add resource clb instance and data clb instances
  CHANGELOG.md
  examples/tencentcloud-clb/main.tf
  examples/tencentcloud-clb/variables.tf
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_clb_attachments.go
  tencentcloud/data_source_tc_clb_attachments_test.go
  tencentcloud/data_source_tc_clb_instances.go
  tencentcloud/data_source_tc_clb_instances_test.go
  tencentcloud/data_source_tc_clb_listener_rules.go
  tencentcloud/data_source_tc_clb_listener_rules_test.go
  tencentcloud/data_source_tc_clb_listeners.go
  tencentcloud/data_source_tc_clb_listeners_test.go
  tencentcloud/data_source_tc_clb_redirections.go
  tencentcloud/data_source_tc_clb_redirections_test.go
  tencentcloud/extension_clb.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_attachment_test.go
  tencentcloud/resource_tc_clb_instance.go
  tencentcloud/resource_tc_clb_instance_test.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  tencentcloud/resource_tc_clb_listener_rule_test.go
  tencentcloud/resource_tc_clb_listener_test.go
  tencentcloud/resource_tc_clb_redirection.go
  tencentcloud/resource_tc_clb_redirection_test.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_mysql_instance.go
  tencentcloud/service_lb.go
  tencentcloud/service_tencentcloud_clb.go
  tencentcloud/service_tencentcloud_redis.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
  vendor/modules.txt
  website/docs/d/clb_attachments.html.markdown
  website/docs/d/clb_instances.html.markdown
  website/docs/d/clb_listener_rules.html.markdown
  website/docs/d/clb_listeners.html.markdown
  website/docs/d/clb_redirections.html.markdown
  website/docs/r/alb_server_attachment.html.markdown
  website/docs/r/clb_attachment.html.markdown
  website/docs/r/clb_instance.html.markdown
  website/docs/r/clb_listener.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
  website/docs/r/clb_redirection.html.markdown
  website/docs/r/lb.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#88 Fix doc directory
  tencentcloud/provider.go
Labels: size/XS

#89 fixed rule_id with clb_attachment
  examples/tencentcloud-clb/main.tf
  tencentcloud/data_source_tc_clb_attachments_test.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_attachment_test.go
  tencentcloud/resource_tc_clb_listener_rule.go
  website/docs/d/clb_attachments.html.markdown
  website/docs/d/clb_listener_rules.html.markdown
  website/docs/d/clb_redirections.html.markdown
  website/docs/r/clb_attachment.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
  website/docs/r/clb_redirection.html.markdown
Labels: documentation, size/M

#90 add deprecated message
  tencentcloud/data_source_tc_route_table.go
  tencentcloud/data_source_tc_security_group.go
  tencentcloud/data_source_tc_subnet.go
  tencentcloud/data_source_tc_vpc.go
  tencentcloud/resource_tc_alb_server_attachment.go
  tencentcloud/resource_tc_lb.go
  tencentcloud/resource_tc_route_entry.go
Labels: size/S

#92 Lb dev
  tencentcloud/data_source_tc_clb_attachments.go
  tencentcloud/data_source_tc_clb_instances.go
  tencentcloud/data_source_tc_clb_listener_rules.go
  tencentcloud/data_source_tc_clb_listeners.go
  tencentcloud/data_source_tc_clb_redirections.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  tencentcloud/resource_tc_clb_redirection.go
  website/docs/d/clb_instances.html.markdown
  website/docs/d/clb_listener_rules.html.markdown
  website/docs/d/clb_listeners.html.markdown
  website/docs/r/clb_attachment.html.markdown
  website/docs/r/clb_listener.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
Labels: documentation, size/M

#93 add retry on cbs
  go.mod
  go.sum
  tencentcloud/common.go
  tencentcloud/data_source_tc_as_scaling_policies.go
  tencentcloud/data_source_tc_cbs_snapshots.go
  tencentcloud/data_source_tc_cbs_storages.go
  tencentcloud/resource_tc_cbs_snapshot.go
  tencentcloud/resource_tc_cbs_snapshot_policy.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_cbs_storage_attachment.go
  vendor/github.com/likexian/gokit/LICENSE
  vendor/github.com/likexian/gokit/assert/README.md
  vendor/github.com/likexian/gokit/assert/assert.go
  vendor/github.com/likexian/gokit/assert/values.go
  vendor/github.com/spf13/afero/.travis.yml
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
  vendor/modules.txt
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#96 fixed instance retry
  tencentcloud/resource_tc_instance.go
Labels: size/S

#97 Lb dev
  go.sum
  tencentcloud/data_source_tc_clb_instances.go
  tencentcloud/data_source_tc_clb_instances_test.go
  tencentcloud/data_source_tc_clb_listener_rules.go
  tencentcloud/data_source_tc_clb_listeners.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_instance.go
  tencentcloud/resource_tc_clb_instance_test.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  tencentcloud/resource_tc_clb_listener_test.go
  tencentcloud/service_tencentcloud_clb.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
  website/docs/d/clb_instances.html.markdown
  website/docs/d/clb_listener_rules.html.markdown
  website/docs/d/clb_listeners.html.markdown
  website/docs/r/clb_instance.html.markdown
  website/docs/r/clb_listener.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
Labels: dependencies, documentation, size/XL

#98 ratelimit and remove redis completely
  go.mod
  go.sum
  tencentcloud/ratelimit/config.go
  tencentcloud/ratelimit/limit.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/service_tencentcloud_as.go
  tencentcloud/service_tencentcloud_cbs.go
  tencentcloud/service_tencentcloud_ccn.go
  tencentcloud/service_tencentcloud_clb.go
  tencentcloud/service_tencentcloud_cos.go
  tencentcloud/service_tencentcloud_dc.go
  tencentcloud/service_tencentcloud_dcg.go
  tencentcloud/service_tencentcloud_mongodb.go
  tencentcloud/service_tencentcloud_mysql.go
  tencentcloud/service_tencentcloud_redis.go
  tencentcloud/service_tencentcloud_vpc.go
  vendor/github.com/yangwenmai/ratelimit/LICENSE
  vendor/github.com/yangwenmai/ratelimit/simpleratelimit/ratelimit.go
  vendor/modules.txt
Labels: dependencies, size/XL

#100 set cpf.Language = "en-US"
  tencentcloud/connectivity/client.go
Labels: size/XS

#101 The `tencentcloud_instance.image_id` property becomes ForceNew.
  CHANGELOG.md
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_instance_test.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/M

#99 add retry with resources and datas in clb
  CHANGELOG.md
  go.mod
  go.sum
  tencentcloud/data_source_tc_clb_attachments.go
  tencentcloud/data_source_tc_clb_instances.go
  tencentcloud/data_source_tc_clb_listener_rules.go
  tencentcloud/data_source_tc_clb_listeners.go
  tencentcloud/data_source_tc_clb_redirections.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_instance.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  tencentcloud/resource_tc_clb_listener_test.go
  tencentcloud/resource_tc_clb_redirection.go
  tencentcloud/service_tencentcloud_clb.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/modules.txt
  website/docs/d/clb_attachments.html.markdown
  website/docs/d/clb_listener_rules.html.markdown
  website/docs/d/clb_listeners.html.markdown
  website/docs/r/clb_attachment.html.markdown
  website/docs/r/clb_instance.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
  website/docs/r/instance.html.markdown
Labels: dependencies, documentation, size/XXL

#103 change rewrite_source_rule_id/rewrite_target_rule_id to source_listener_rule_id/target_listener_rule_id
  examples/tencentcloud-clb/main.tf
  go.sum
  tencentcloud/data_source_tc_clb_redirections.go
  tencentcloud/data_source_tc_clb_redirections_test.go
  tencentcloud/resource_tc_clb_redirection.go
  tencentcloud/resource_tc_clb_redirection_test.go
  tencentcloud/service_tencentcloud_clb.go
  website/docs/d/clb_redirections.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
  website/docs/r/clb_redirection.html.markdown
Labels: documentation, size/M

#104 get elegant way of id creation
  examples/tencentcloud-clb/main.tf
  tencentcloud/data_source_tc_clb_attachments.go
  tencentcloud/data_source_tc_clb_listener_rules.go
  tencentcloud/data_source_tc_clb_listeners.go
  tencentcloud/data_source_tc_clb_redirections.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_instance.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  tencentcloud/resource_tc_clb_listener_rule_test.go
  tencentcloud/resource_tc_clb_listener_test.go
  tencentcloud/resource_tc_clb_redirection.go
  tencentcloud/service_tencentcloud_clb.go
  website/docs/d/clb_attachments.html.markdown
  website/docs/d/clb_listener_rules.html.markdown
  website/docs/d/clb_listeners.html.markdown
  website/docs/d/clb_redirections.html.markdown
  website/docs/r/clb_attachment.html.markdown
  website/docs/r/clb_instance.html.markdown
  website/docs/r/clb_listener.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
  website/docs/r/clb_redirection.html.markdown
Labels: documentation, size/XL

#105 fixed spaces in docs
  tencentcloud/common.go
  tencentcloud/data_source_tc_clb_attachments.go
  tencentcloud/data_source_tc_clb_listeners.go
  tencentcloud/data_source_tc_clb_redirections.go
  tencentcloud/resource_tc_clb_attachment.go
  website/docs/d/clb_attachments.html.markdown
  website/docs/d/clb_listeners.html.markdown
  website/docs/r/clb_attachment.html.markdown
Labels: documentation, size/S

#107 fixed printf error
  tencentcloud/common.go
Labels: size/XS

#106 fixed as bind clb
  tencentcloud/resource_tc_as_scaling_group.go
  tencentcloud/resource_tc_clb_listener_rule.go
  website/docs/r/as_scaling_group.html.markdown
Labels: documentation, size/M

#108 rename listener_rule_id as rule_id
  examples/tencentcloud-clb/main.tf
  tencentcloud/data_source_tc_clb_attachments.go
  tencentcloud/data_source_tc_clb_attachments_test.go
  tencentcloud/data_source_tc_clb_instances.go
  tencentcloud/data_source_tc_clb_listener_rules.go
  tencentcloud/data_source_tc_clb_listener_rules_test.go
  tencentcloud/data_source_tc_clb_listeners.go
  tencentcloud/data_source_tc_clb_redirections.go
  tencentcloud/data_source_tc_clb_redirections_test.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_instance.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  tencentcloud/resource_tc_clb_redirection.go
  tencentcloud/resource_tc_clb_redirection_test.go
  tencentcloud/service_tencentcloud_clb.go
  website/docs/d/clb_attachments.html.markdown
  website/docs/d/clb_instances.html.markdown
  website/docs/d/clb_listener_rules.html.markdown
  website/docs/d/clb_listeners.html.markdown
  website/docs/d/clb_redirections.html.markdown
  website/docs/r/clb_attachment.html.markdown
  website/docs/r/clb_instance.html.markdown
  website/docs/r/clb_listener.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
  website/docs/r/clb_redirection.html.markdown
Labels: documentation, size/XL

#109 retry on status code error
  CHANGELOG.md
  tencentcloud/common.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_cbs_storage_attachment_test.go
  tencentcloud/resource_tc_instance.go
Labels: size/S

#111 support tke(Tencent Kubernetes Engine)
  CHANGELOG.md
  examples/tencentcloud-clb/main.tf
  examples/tencentcloud-tke/main.tf
  examples/tencentcloud-tke/variables.tf
  go.sum
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_container_cluster_instances.go
  tencentcloud/data_source_tc_container_clusters.go
  tencentcloud/data_source_tc_kubernetes_clusters.go
  tencentcloud/data_source_tc_kubernetes_clusters_test.go
  tencentcloud/extension_tke.go
  tencentcloud/helper.go
  tencentcloud/provider.go
  tencentcloud/ratelimit/limit.go
  tencentcloud/resource_tc_container_cluster.go
  tencentcloud/resource_tc_container_cluster_instance.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_cluster_test.go
  tencentcloud/resource_tc_kubernetes_scale_worker.go
  tencentcloud/resource_tc_kubernetes_scale_worker_test.go
  tencentcloud/service_tencencloud_tke.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
  vendor/modules.txt
  website/docs/d/container_cluster_instances.html.markdown
  website/docs/d/container_clusters.html.markdown
  website/docs/d/kubernetes_clusters.html.markdown
  website/docs/r/container_cluster.html.markdown
  website/docs/r/container_cluster_instance.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_scale_worker.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#112 add detail and default value in para description
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  website/docs/r/clb_listener.html.markdown
  website/docs/r/clb_listener_rule.html.markdown
Labels: documentation, size/XS

#113 add log elapsed for cvm
  tencentcloud/data_source_tc_availability_zones.go
  tencentcloud/data_source_tc_eip.go
  tencentcloud/data_source_tc_eip_test.go
  tencentcloud/data_source_tc_image.go
  tencentcloud/data_source_tc_instance_types.go
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_eip_association.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_key_pair.go
Labels: size/S

#117 fix issue #116
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#119 Add limitations to tag key name.
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#120 refactor resource cvm instance
  CHANGELOG.md
  tencentcloud/connectivity/client.go
  tencentcloud/extension_cvm.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_instance_test.go
  tencentcloud/service_instance.go
  tencentcloud/service_key_pair.go
  tencentcloud/service_tencentcloud_cvm.go
  tencentcloud/service_tencentcloud_tag.go
  tencentcloud/validators.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/models.go
  vendor/modules.txt
  website/docs/r/instance.html.markdown
Labels: dependencies, documentation, size/XXL

#121 fix cvm data disk missing computed
  CHANGELOG.md
  tencentcloud/resource_tc_instance.go
Labels: size/XS

#122 problem handling caused by mysql API update.
  CHANGELOG.md
  tencentcloud/resource_tc_mysql_backup_policy.go
  tencentcloud/resource_tc_mysql_backup_policy_test.go
  tencentcloud/service_tencentcloud_mysql.go
  website/docs/r/mysql_backup_policy.html.markdown
Labels: documentation, size/S

#123 kubernetes cgi error retry.
  CHANGELOG.md
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_scale_worker.go
Labels: size/XS
