Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2020-01, with the labels that each got.

#292 `tencentcloud_redis_instance` field security_groups are id list,not name list
  CHANGELOG.md
  tencentcloud/service_tencentcloud_redis.go
Labels: size/XS

#293 fixed image created_time is string
  tencentcloud/data_source_tc_images.go
Labels: size/XS

#295 Fix type of cvm memory_size and cbs attached
  tencentcloud/data_source_tc_instance_types.go
  tencentcloud/resource_tc_cbs_storage.go
Labels: size/XS

#294 docs: fix doc
  tencentcloud/data_source_tc_gaap_certificates.go
  tencentcloud/data_source_tc_gaap_http_rules.go
  tencentcloud/data_source_tc_gaap_layer4_listeners.go
  tencentcloud/data_source_tc_gaap_layer7_listeners.go
  tencentcloud/data_source_tc_gaap_proxies.go
  tencentcloud/data_source_tc_gaap_realservers.go
  tencentcloud/resource_tc_gaap_certificate.go
  tencentcloud/resource_tc_gaap_http_domain.go
  tencentcloud/resource_tc_gaap_http_rule.go
  tencentcloud/resource_tc_gaap_layer4_listener.go
  tencentcloud/resource_tc_gaap_layer7_listener.go
  tencentcloud/resource_tc_gaap_proxy.go
  tencentcloud/resource_tc_gaap_realserver.go
  tencentcloud/resource_tc_gaap_security_policy.go
  tencentcloud/resource_tc_gaap_security_rule.go
  website/docs/d/gaap_certificates.html.markdown
  website/docs/d/gaap_http_rules.html.markdown
  website/docs/d/gaap_layer4_listeners.html.markdown
  website/docs/d/gaap_layer7_listeners.html.markdown
  website/docs/d/gaap_proxies.html.markdown
  website/docs/d/gaap_realservers.html.markdown
  website/docs/r/gaap_certificate.html.markdown
  website/docs/r/gaap_http_domain.html.markdown
  website/docs/r/gaap_http_rule.html.markdown
  website/docs/r/gaap_layer4_listener.html.markdown
  website/docs/r/gaap_layer7_listener.html.markdown
  website/docs/r/gaap_proxy.html.markdown
  website/docs/r/gaap_realserver.html.markdown
  website/docs/r/gaap_security_policy.html.markdown
  website/docs/r/gaap_security_rule.html.markdown
Labels: documentation, size/L

#289 Add DAYU resources and datas
  CHANGELOG.md
  examples/tencentcloud-dayu/main.tf
  examples/tencentcloud-dayu/variables.tf
  go.mod
  go.sum
  tencentcloud/basic_test.go
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_dayu_cc_http_policies.go
  tencentcloud/data_source_tc_dayu_cc_http_policies_test.go
  tencentcloud/data_source_tc_dayu_cc_https_policies.go
  tencentcloud/data_source_tc_dayu_cc_https_policies_test.go
  tencentcloud/data_source_tc_dayu_ddos_policies.go
  tencentcloud/data_source_tc_dayu_ddos_policies_test.go
  tencentcloud/data_source_tc_dayu_ddos_policy_attachments.go
  tencentcloud/data_source_tc_dayu_ddos_policy_attachments_test.go
  tencentcloud/data_source_tc_dayu_ddos_policy_cases.go
  tencentcloud/data_source_tc_dayu_ddos_policy_cases_test.go
  tencentcloud/data_source_tc_dayu_l4_rules.go
  tencentcloud/data_source_tc_dayu_l4_rules_test.go
  tencentcloud/data_source_tc_dayu_l7_rules.go
  tencentcloud/data_source_tc_dayu_l7_rules_test.go
  tencentcloud/extension_dayu.go
  tencentcloud/internal/helper/transform.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_dayu_cc_http_policy.go
  tencentcloud/resource_tc_dayu_cc_http_policy_test.go
  tencentcloud/resource_tc_dayu_cc_https_policy.go
  tencentcloud/resource_tc_dayu_cc_https_policy_test.go
  tencentcloud/resource_tc_dayu_ddos_policy.go
  tencentcloud/resource_tc_dayu_ddos_policy_attachment.go
  tencentcloud/resource_tc_dayu_ddos_policy_attachment_test.go
  tencentcloud/resource_tc_dayu_ddos_policy_case.go
  tencentcloud/resource_tc_dayu_ddos_policy_case_test.go
  tencentcloud/resource_tc_dayu_ddos_policy_test.go
  tencentcloud/resource_tc_dayu_l4_rule.go
  tencentcloud/resource_tc_dayu_l4_rule_test.go
  tencentcloud/resource_tc_dayu_l7_rule.go
  tencentcloud/resource_tc_dayu_l7_rule_test.go
  tencentcloud/service_tencentcloud_dayu.go
  tencentcloud/validators.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dayu/v20180709/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dayu/v20180709/models.go
  vendor/modules.txt
  website/docs/d/dayu_cc_http_policies.html.markdown
  website/docs/d/dayu_cc_https_policies.html.markdown
  website/docs/d/dayu_ddos_policies.html.markdown
  website/docs/d/dayu_ddos_policy_attachments.html.markdown
  website/docs/d/dayu_ddos_policy_cases.html.markdown
  website/docs/d/dayu_l4_rules.html.markdown
  website/docs/d/dayu_l7_rules.html.markdown
  website/docs/r/dayu_cc_http_policy.html.markdown
  website/docs/r/dayu_cc_https_policy.html.markdown
  website/docs/r/dayu_ddos_policy.html.markdown
  website/docs/r/dayu_ddos_policy_attachment.html.markdown
  website/docs/r/dayu_ddos_policy_case.html.markdown
  website/docs/r/dayu_l4_rule.html.markdown
  website/docs/r/dayu_l7_rule.html.markdown
  website/tencentcloud.erb
Labels: size/XXL

#302 name and size change
  tencentcloud/data_source_tc_mysql_instance_test.go
Labels: size/XS

#307 Validate lenth of utf8 rune not byte
  tencentcloud/validators.go
Labels: size/XS

#306 fix detach may cause error
  CHANGELOG.md
  tencentcloud/service_tencentcloud_vpc.go
Labels: size/M

#311 err solute.
  tencentcloud/resource_tc_dayu_ddos_policy_attachment_test.go
  tencentcloud/resource_tc_eip_association_test.go
  tencentcloud/service_tencentcloud_mysql.go
Labels: size/XS

#305 Fix bug that query status failed and the error processes
  CHANGELOG.md
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_dayu_l7_rule.go
  tencentcloud/resource_tc_vpn_gateway.go
  tencentcloud/service_tencentcloud_clb.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
Labels: dependencies, size/XL

#299 fix data source security group project id type error
  CHANGELOG.md
  tencentcloud/data_source_tc_security_group.go
Labels: size/XS

#310 Fix as test fail
  CHANGELOG.md
  tencentcloud/resource_tc_as_attachment_test.go
  tencentcloud/resource_tc_as_lifecycle_hook_test.go
  tencentcloud/resource_tc_as_scaling_config_test.go
  tencentcloud/resource_tc_as_scaling_group.go
  tencentcloud/resource_tc_as_scaling_group_test.go
  tencentcloud/resource_tc_as_scaling_policy_test.go
  tencentcloud/resource_tc_as_schedule.go
  tencentcloud/resource_tc_as_schedule_test.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/service_tencentcloud_as.go
Labels: size/L

#313 FIX BUG: Resource: `tencentcloud_vpn_gateway` of postpaid charge type cannot be deleted normally
  CHANGELOG.md
  tencentcloud/resource_tc_vpn_gateway.go
Labels: size/XS

#316 fix: data source tencentcloud_security_groups project_id filter
  CHANGELOG.md
  tencentcloud/data_source_tc_security_groups.go
  tencentcloud/data_source_tc_security_groups_test.go
Labels: size/S

#318 optimize gaap service
  CHANGELOG.md
  tencentcloud/data_source_tc_gaap_certificates_test.go
  tencentcloud/data_source_tc_gaap_proxies_test.go
  tencentcloud/data_source_tc_gaap_realservers_test.go
  tencentcloud/resource_tc_gaap_certificate_test.go
  tencentcloud/resource_tc_gaap_proxy_test.go
  tencentcloud/service_tencentcloud_gaap.go
Labels: size/M

#317 Fix VPN read nil issue
  CHANGELOG.md
  tencentcloud/data_source_tc_vpn_gateways.go
  tencentcloud/resource_tc_ha_vip.go
  tencentcloud/resource_tc_ha_vip_eip_attachment.go
  tencentcloud/resource_tc_ha_vip_eip_attachment_test.go
  tencentcloud/resource_tc_vpn_connection.go
  tencentcloud/resource_tc_vpn_customer_gateway.go
  tencentcloud/resource_tc_vpn_gateway.go
  tencentcloud/service_tencentcloud_ssl.go
  tencentcloud/service_tencentcloud_vpc.go
  tencentcloud/validators.go
Labels: size/M

#320 Check build in all platform
  .githooks/pre-commit
  .travis.yml
  GNUmakefile
  website/docs/d/as_scaling_groups.html.markdown
  website/docs/r/instance.html.markdown
Labels: documentation, size/S

#321 travis ci remove test other platform
  .travis.yml
Labels: size/XS

#323 solute some unhandled errors and some missing codes.
  tencentcloud/data_source_tc_clb_instances.go
  tencentcloud/resource_tc_alb_server_attachment.go
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_ha_vip_eip_attachment.go
  tencentcloud/resource_tc_security_group_rule.go
  tencentcloud/resource_tc_tcaplus_table.go
  tencentcloud/service_tencentcloud_clb.go
  tencentcloud/service_tencentcloud_dayu.go
  tencentcloud/service_tencentcloud_mysql.go
  tencentcloud/service_tencentcloud_tke.go
Labels: size/M

#328 Key pair support regular expression search
  CHANGELOG.md
  tencentcloud/data_source_tc_cbs_snapshots.go
  tencentcloud/data_source_tc_cbs_storages.go
  tencentcloud/data_source_tc_clb_instances.go
  tencentcloud/data_source_tc_gaap_proxies.go
  tencentcloud/data_source_tc_instances.go
  tencentcloud/data_source_tc_key_pairs.go
  tencentcloud/data_source_tc_key_pairs_test.go
  tencentcloud/data_source_tc_redis_instances.go
  website/docs/d/key_pairs.html.markdown
Labels: documentation, size/M

#325 fix: fix scf data source panic
  examples/tencentcloud-vpn/main.tf
  tencentcloud/basic_test.go
  tencentcloud/data_source_tc_scf_functions.go
  tencentcloud/data_source_tc_scf_functions_test.go
  tencentcloud/data_source_tc_scf_namespaces.go
  tencentcloud/resource_tc_scf_function.go
  tencentcloud/resource_tc_scf_function_test.go
  tencentcloud/service_tencentcloud_scf.go
  website/docs/d/scf_namespaces.html.markdown
Labels: documentation, size/L

#331 pull redis available zone from the interface of CVM
  tencentcloud/data_source_tc_mysql_instance.go
  tencentcloud/extension_redis.go
  tencentcloud/internal/helper/transform.go
  tencentcloud/resource_tc_as_scaling_group.go
  tencentcloud/resource_tc_clb_listener.go
  tencentcloud/resource_tc_clb_listener_rule.go
  tencentcloud/resource_tc_eni_attachment_test.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_scale_worker_test.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/resource_tc_route_table_entry.go
  tencentcloud/service_tencentcloud_redis.go
  website/docs/d/mysql_instance.html.markdown
  website/docs/r/as_scaling_group.html.markdown
Labels: documentation, size/L

#333 fix bugs that resource `dnat` `elastic_port` `internal_port` type error;
  CHANGELOG.md
  tencentcloud/resource_tc_dayu_cc_https_policy.go
  tencentcloud/resource_tc_dayu_ddos_policy.go
  tencentcloud/resource_tc_dayu_ddos_policy_attachment.go
  tencentcloud/resource_tc_dayu_ddos_policy_case.go
  tencentcloud/resource_tc_dayu_l4_rule.go
  tencentcloud/resource_tc_dayu_l7_rule.go
  tencentcloud/resource_tc_dnat.go
  tencentcloud/resource_tc_vpn_gateway.go
  website/docs/r/dayu_ddos_policy.html.markdown
Labels: documentation, size/S
