Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2020-05, with the labels that each got.

#404 fixed example of tcaplus_application
  tencentcloud/resource_tc_tcaplus_application.go
  website/docs/r/tcaplus_application.html.markdown
Labels: documentation, size/XS

#407 cdn domain add cache_key
  CHANGELOG.md
  tencentcloud/extension_cdn.go
  tencentcloud/resource_tc_cdn_domain.go
  tencentcloud/resource_tc_cdn_domain_test.go
  tencentcloud/service_tencentcloud_cdn.go
  website/docs/r/cdn_domain.html.markdown
Labels: documentation, size/M

#412 Fix for some minor language issues.
  website/docs/index.html.markdown
Labels: documentation, size/XS

#409 add soft delete with CBS and CVM
  CHANGELOG.md
  tencentcloud/data_source_tc_cbs_storages.go
  tencentcloud/data_source_tc_cbs_storages_test.go
  tencentcloud/data_source_tc_instances.go
  tencentcloud/extension_cbs.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_cbs_storage_test.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_instance_test.go
  tencentcloud/service_tencentcloud_cbs.go
  tencentcloud/service_tencentcloud_cvm.go
  website/docs/d/cbs_storages.html.markdown
  website/docs/d/instances.html.markdown
  website/docs/r/cbs_storage.html.markdown
Labels: documentation, size/XL

#414 add STS
  tencentcloud/connectivity/client.go
  tencentcloud/provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/sts/v20180813/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/sts/v20180813/models.go
  vendor/modules.txt
  website/docs/d/monitor_policy_conditions.html.markdown
  website/docs/d/monitor_product_event.html.markdown
  website/docs/d/monitor_product_namespace.html.markdown
  website/docs/index.html.markdown
  website/docs/r/monitor_policy_group.html.markdown
Labels: dependencies, documentation, size/XL

#419 [support vpngw bound to ccn instance]
  CHANGELOG.md
  examples/tencentcloud-ccn/main.tf
  examples/tencentcloud-ccn/variables.tf
  examples/tencentcloud-vpn/main.tf
  tencentcloud/data_source_tc_ccn_instances.go
  tencentcloud/data_source_tc_vpn_gateways.go
  tencentcloud/extension_cnn.go
  tencentcloud/resource_tc_ccn_attachment.go
  tencentcloud/resource_tc_ccn_attachment_test.go
  tencentcloud/resource_tc_vpn_gateway.go
  tencentcloud/resource_tc_vpn_gateway_test.go
  website/docs/d/ccn_instances.html.markdown
  website/docs/d/vpn_gateways.html.markdown
  website/docs/r/ccn_attachment.html.markdown
  website/docs/r/vpn_gateway.html.markdown
Labels: documentation, size/L

#418 fix cdn domain https config product inconsistency after apply
  CHANGELOG.md
  tencentcloud/extension_cdn.go
  tencentcloud/resource_tc_cdn_domain.go
  tencentcloud/resource_tc_cdn_domain_test.go
  website/docs/r/cdn_domain.html.markdown
Labels: documentation, size/L

#420 rewrite tcaplus names.
  CHANGELOG.md
  tencentcloud/data_source_tc_tcaplus_applications.go
  tencentcloud/data_source_tc_tcaplus_applications_test.go
  tencentcloud/data_source_tc_tcaplus_idls.go
  tencentcloud/data_source_tc_tcaplus_idls_test.go
  tencentcloud/data_source_tc_tcaplus_tables.go
  tencentcloud/data_source_tc_tcaplus_tables_test.go
  tencentcloud/data_source_tc_tcaplus_zones.go
  tencentcloud/data_source_tc_tcaplus_zones_test.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_tcaplus_application.go
  tencentcloud/resource_tc_tcaplus_application_test.go
  tencentcloud/resource_tc_tcaplus_idl.go
  tencentcloud/resource_tc_tcaplus_idl_test.go
  tencentcloud/resource_tc_tcaplus_table.go
  tencentcloud/resource_tc_tcaplus_table_test.go
  tencentcloud/resource_tc_tcaplus_zone.go
  tencentcloud/resource_tc_tcaplus_zone_test.go
  tencentcloud/service_tencentcloud_tcaplus.go
  website/docs/d/tcaplus_clusters.html.markdown
  website/docs/d/tcaplus_groups.html.markdown
  website/docs/d/tcaplus_idls.html.markdown
  website/docs/d/tcaplus_tables.html.markdown
  website/docs/r/tcaplus_cluster.html.markdown
  website/docs/r/tcaplus_group.html.markdown
  website/docs/r/tcaplus_idl.html.markdown
  website/docs/r/tcaplus_table.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XXL

#421 renames tcaplus file names.
  tencentcloud/data_source_tc_tcaplus_clusters.go
  tencentcloud/data_source_tc_tcaplus_clusters_test.go
  tencentcloud/data_source_tc_tcaplus_groups.go
  tencentcloud/data_source_tc_tcaplus_groups_test.go
  tencentcloud/resource_tc_tcaplus_cluster.go
  tencentcloud/resource_tc_tcaplus_cluster_test.go
  tencentcloud/resource_tc_tcaplus_group.go
  tencentcloud/resource_tc_tcaplus_group_test.go
Labels: size/XS

#428 fix pass case
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_cbs_storage_test.go
Labels: size/XS

#429 change order of resources in provider.go
  CHANGELOG.md
  tencentcloud/provider.go
Labels: size/M

#431 Support elasticsearch
  CHANGELOG.md
  examples/tencentcloud-elasticsearch/main.tf
  examples/tencentcloud-elasticsearch/variables.tf
  examples/tencentcloud-elasticsearch/version.tf
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_elasticsearch_instances.go
  tencentcloud/data_source_tc_elasticsearch_instances_test.go
  tencentcloud/extension_elasticsearch.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_elasticsearch_instance.go
  tencentcloud/resource_tc_elasticsearch_instance_test.go
  tencentcloud/service_tencentcloud_elasticsearch.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/es/v20180416/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/es/v20180416/models.go
  vendor/modules.txt
  website/docs/d/elasticsearch_instances.html.markdown
  website/docs/r/elasticsearch_instance.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL
