Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2020-06, with the labels that each got.

#434 Remove validate function of bandwidth
  CHANGELOG.md
  tencentcloud/resource_tc_as_scaling_config.go
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_gaap_proxy.go
  tencentcloud/resource_tc_kubernetes_as_scaling_group.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_vpn_gateway.go
  website/docs/r/eip.html.markdown
  website/docs/r/vpn_gateway.html.markdown
Labels: documentation, size/M

#436 support when the client certificate id is empty
  tencentcloud/resource_tc_gaap_http_domain.go
Labels: size/XS

#432 support prepay charge type and force_delete for resource_mysql_instance
  CHANGELOG.md
  tencentcloud/basic_test.go
  tencentcloud/data_source_tc_mysql_instance.go
  tencentcloud/data_source_tc_mysql_instance_test.go
  tencentcloud/extension_mysql.go
  tencentcloud/resource_tc_mysql_instance.go
  tencentcloud/resource_tc_mysql_instance_test.go
  tencentcloud/resource_tc_mysql_readonly_instance.go
  tencentcloud/resource_tc_mysql_readonly_instance_test.go
  website/docs/d/mysql_instance.html.markdown
  website/docs/r/mysql_instance.html.markdown
  website/docs/r/mysql_readonly_instance.html.markdown
Labels: documentation, size/XL

#435 [redis instance supports prepaid type]
  CHANGELOG.md
  examples/tencentcloud-redis/main.tf
  examples/tencentcloud-vpn/main.tf
  tencentcloud/data_source_tc_redis_instances.go
  tencentcloud/data_source_tc_redis_instances_test.go
  tencentcloud/extension_redis.go
  tencentcloud/resource_tc_redis_backup_config_test.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/resource_tc_redis_instance_test.go
  tencentcloud/service_tencentcloud_redis.go
  website/docs/d/redis_instances.html.markdown
  website/docs/r/redis_instance.html.markdown
Labels: documentation, size/XL

#438 Fix cvm instance inconsistency when eip is attached to the cvm
  CHANGELOG.md
  tencentcloud/connectivity/client.go
  tencentcloud/resource_tc_instance.go
Labels: size/S

#439 tcaplus change field name and des.
  CHANGELOG.md
  examples/tencentcloud-tcaplus/main.tf
  examples/tencentcloud-tcaplus/variables.tf
  main.go
  tencentcloud/data_source_tc_tcaplus_clusters.go
  tencentcloud/data_source_tc_tcaplus_idls.go
  tencentcloud/data_source_tc_tcaplus_idls_test.go
  tencentcloud/data_source_tc_tcaplus_tablegroups.go
  tencentcloud/data_source_tc_tcaplus_tablegroups_test.go
  tencentcloud/data_source_tc_tcaplus_tables.go
  tencentcloud/data_source_tc_tcaplus_tables_test.go
  tencentcloud/extension_tcaplus.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_cos_bucket_object_test.go
  tencentcloud/resource_tc_dayu_l7_rule.go
  tencentcloud/resource_tc_dc_gateway_ccn_route_test.go
  tencentcloud/resource_tc_dc_gateway_test.go
  tencentcloud/resource_tc_kubernetes_scale_worker_test.go
  tencentcloud/resource_tc_tcaplus_cluster.go
  tencentcloud/resource_tc_tcaplus_idl.go
  tencentcloud/resource_tc_tcaplus_idl_test.go
  tencentcloud/resource_tc_tcaplus_table.go
  tencentcloud/resource_tc_tcaplus_table_test.go
  tencentcloud/resource_tc_tcaplus_tablegroup.go
  tencentcloud/resource_tc_tcaplus_tablegroup_test.go
  tencentcloud/service_tencentcloud_ccn.go
  tencentcloud/service_tencentcloud_redis.go
  website/docs/d/tcaplus_applications.html.markdown
  website/docs/d/tcaplus_clusters.html.markdown
  website/docs/d/tcaplus_groups.html.markdown
  website/docs/d/tcaplus_idls.html.markdown
  website/docs/d/tcaplus_tablegroups.html.markdown
  website/docs/d/tcaplus_tables.html.markdown
  website/docs/d/tcaplus_zones.html.markdown
  website/docs/r/tcaplus_application.html.markdown
  website/docs/r/tcaplus_cluster.html.markdown
  website/docs/r/tcaplus_group.html.markdown
  website/docs/r/tcaplus_idl.html.markdown
  website/docs/r/tcaplus_table.html.markdown
  website/docs/r/tcaplus_tablegroup.html.markdown
  website/docs/r/tcaplus_zone.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XXL

#443 vpc DescribeVpcs panic
  tencentcloud/resource_tc_cdn_domain.go
  tencentcloud/resource_tc_dayu_ddos_policy.go
  tencentcloud/service_tencentcloud_vpc.go
Labels: size/XS

#444 upgrade go mod
  go.mod
  go.sum
  vendor/github.com/agext/levenshtein/.travis.yml
  vendor/github.com/agext/levenshtein/README.md
  vendor/github.com/agext/levenshtein/levenshtein.go
  vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
  vendor/github.com/hashicorp/hcl/v2/diagnostic.go
  vendor/github.com/hashicorp/hcl/v2/hcldec/spec.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/parser.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource_data.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/serialize.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cam/v20190116/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cam/v20190116/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdn/v20180606/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdn/v20180606/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/monitor/v20180724/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/scf/v20180416/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcaplusdb/v20190823/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/github.com/zclconf/go-cty/cty/convert/conversion.go
  vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go
  vendor/github.com/zclconf/go-cty/cty/convert/unify.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/collection.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/conversion.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/datetime.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/format.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/json.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/number.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/set.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/string.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/string_replace.go
  vendor/github.com/zclconf/go-cty/cty/path.go
  vendor/github.com/zclconf/go-cty/cty/path_set.go
  vendor/github.com/zclconf/go-cty/cty/set/rules.go
  vendor/github.com/zclconf/go-cty/cty/set/set.go
  vendor/github.com/zclconf/go-cty/cty/set_internals.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#445 tencentcloud_kubernetes_cluster support labels
  CHANGELOG.md
  examples/tencentcloud-tke/main.tf
  tencentcloud/resource_tc_kubernetes_as_scaling_group.go
  tencentcloud/resource_tc_kubernetes_as_scaling_group_test.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_cluster_attachment.go
  tencentcloud/resource_tc_kubernetes_cluster_attachment_test.go
  tencentcloud/resource_tc_kubernetes_cluster_test.go
  tencentcloud/service_tencentcloud_tke.go
  website/docs/r/kubernetes_as_scaling_group.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_cluster_attachment.html.markdown
Labels: documentation, size/L

#447 fix deal error for kubernetes as group Read
  tencentcloud/resource_tc_kubernetes_as_scaling_group.go
Labels: size/XS

#448 cos bucket support encryption and versioning
  CHANGELOG.md
  tencentcloud/resource_tc_cos_bucket.go
  tencentcloud/resource_tc_cos_bucket_test.go
  tencentcloud/resource_tc_scf_function.go
  tencentcloud/resource_tc_ssl_certificate.go
  tencentcloud/service_tencentcloud_cos.go
  website/docs/r/cos_bucket.html.markdown
  website/docs/r/scf_function.html.markdown
Labels: documentation, size/L

#450 [add zone config datasource for sqlserver]
  CHANGELOG.md
  examples/tencentcloud-sqlserver/main.tf
  examples/tencentcloud-sqlserver/variable.tf
  examples/tencentcloud-sqlserver/version.tf
  go.sum
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_sqlserver_zone_config.go
  tencentcloud/data_source_tc_sqlserver_zone_config_test.go
  tencentcloud/extension_sqlserver.go
  tencentcloud/provider.go
  tencentcloud/service_tencentcloud_sqlserver.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/sqlserver/v20180328/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/sqlserver/v20180328/models.go
  vendor/modules.txt
  website/docs/d/sqlserver_zone_config.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#449 add resrouce `tencentcloud_postgresql_instance`;
  CHANGELOG.md
  examples/tencentcloud-postgresql/main.tf
  examples/tencentcloud-postgresql/variables.tf
  examples/tencentcloud-postgresql/version.tf
  go.mod
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_postgresql_instances.go
  tencentcloud/data_source_tc_postgresql_instances_test.go
  tencentcloud/data_source_tc_postgresql_specinfos.go
  tencentcloud/data_source_tc_postgresql_specinfos_test.go
  tencentcloud/extension_postgresql.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_postgresql_instance.go
  tencentcloud/resource_tc_postgresql_instance_test.go
  tencentcloud/service_tencentcloud_postgresql.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/postgres/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/postgres/v20170312/models.go
  vendor/modules.txt
  website/docs/d/postgresql_instances.html.markdown
  website/docs/d/postgresql_specinfos.html.markdown
  website/docs/r/postgresql_instance.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#451 optimize about memory and version of postgresql
  go.mod
  go.sum
  tencentcloud/data_source_tc_postgresql_instances.go
  tencentcloud/data_source_tc_postgresql_instances_test.go
  tencentcloud/data_source_tc_postgresql_specinfos.go
  tencentcloud/data_source_tc_postgresql_specinfos_test.go
  tencentcloud/data_source_tc_tcaplus_tablegroups.go
  tencentcloud/data_source_tc_tcaplus_tables.go
  tencentcloud/resource_tc_elasticsearch_instance.go
  tencentcloud/resource_tc_postgresql_instance.go
  tencentcloud/resource_tc_tcaplus_table.go
  vendor/github.com/golang/protobuf/ptypes/empty/empty.pb.go
  vendor/github.com/golang/protobuf/ptypes/empty/empty.proto
  vendor/github.com/hashicorp/go-plugin/client.go
  vendor/github.com/hashicorp/go-plugin/go.mod
  vendor/github.com/hashicorp/go-plugin/go.sum
  vendor/github.com/hashicorp/go-plugin/grpc_client.go
  vendor/github.com/hashicorp/go-plugin/grpc_server.go
  vendor/github.com/hashicorp/go-plugin/grpc_stdio.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/gen.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_broker.pb.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_broker.proto
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_controller.pb.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_stdio.pb.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_stdio.proto
  vendor/github.com/hashicorp/go-plugin/server.go
  vendor/github.com/hashicorp/go-plugin/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cam/v20190116/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdn/v20180606/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dc/v20180410/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/monitor/v20180724/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/scf/v20180416/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/google.golang.org/grpc/reflection/README.md
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.proto
  vendor/google.golang.org/grpc/reflection/serverreflection.go
  vendor/modules.txt
  website/docs/d/postgresql_instances.html.markdown
  website/docs/d/postgresql_specinfos.html.markdown
  website/docs/r/postgresql_instance.html.markdown
Labels: dependencies, documentation, size/XXL

#453 mongodb instance support more machine type
  CHANGELOG.md
  tencentcloud/extension_mongodb.go
  tencentcloud/resource_tc_mongodb_instance.go
  tencentcloud/resource_tc_mongodb_sharding_instance.go
  tencentcloud/service_tencentcloud_sqlserver.go
  website/docs/r/mongodb_instance.html.markdown
  website/docs/r/mongodb_sharding_instance.html.markdown
Labels: documentation, size/M

#452 add cdn datasource
  CHANGELOG.md
  examples/tencentcloud-cdn/main.tf
  tencentcloud/data_source_tc_cdn_domains.go
  tencentcloud/data_source_tc_cdn_domains_test.go
  tencentcloud/extension_cdn.go
  tencentcloud/provider.go
  tencentcloud/service_tencentcloud_cdn.go
  website/docs/d/cdn_domains.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XL

#454 fix a condition for setting client certificate ids
  tencentcloud/resource_tc_gaap_http_domain.go
Labels: size/XS

#455 fix paging logic
  tencentcloud/service_tencentcloud_mysql.go
Labels: size/XS

#456 fix cos creation failure
  CHANGELOG.md
  tencentcloud/resource_tc_cos_bucket.go
Labels: size/XS
