Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2020-07, with the labels that each got.

#461 fix cvm allocate_public_ip inconsistency when eip is attached to the cvm
  CHANGELOG.md
  tencentcloud/resource_tc_instance.go
Labels: size/XS

#458 fix cvm creation while its tags not sync issue
  tencentcloud/common.go
  tencentcloud/resource_tc_instance.go
Labels: size/S

#460 Fix auto-forcenew upgrade tencentcloud-terraform SDK with resource `tencentcloud_mysql_instance`
  CHANGELOG.md
  tencentcloud/resource_tc_mysql_instance.go
  website/docs/r/mysql_instance.html.markdown
  website/docs/r/mysql_readonly_instance.html.markdown
Labels: documentation, size/M

#462 fix cdn resource fields description
  tencentcloud/resource_tc_cdn_domain.go
  website/docs/r/cdn_domain.html.markdown
Labels: documentation, size/XS

#463 fix description
  tencentcloud/data_source_tc_mysql_instance.go
  tencentcloud/resource_tc_mysql_instance.go
  website/docs/d/mysql_instance.html.markdown
  website/docs/r/mysql_instance.html.markdown
  website/docs/r/mysql_readonly_instance.html.markdown
Labels: documentation, size/XS

#464 resource_tc_mysql_instance patch
  tencentcloud/resource_tc_mysql_instance.go
  tencentcloud/resource_tc_mysql_instance_test.go
  tencentcloud/resource_tc_mysql_readonly_instance.go
Labels: size/M

#465 Add worker_config with resource `tencentcloud_kubernetes_cluster_attachment`
  CHANGELOG.md
  tencentcloud/internal/helper/transform.go
  tencentcloud/resource_tc_cam_role.go
  tencentcloud/resource_tc_kubernetes_cluster_attachment.go
  website/docs/r/cam_role.html.markdown
  website/docs/r/kubernetes_cluster_attachment.html.markdown
Labels: documentation, size/L

#471 datasource images support snapshotSet
  CHANGELOG.md
  tencentcloud/data_source_tc_images.go
  tencentcloud/data_source_tc_images_test.go
  tencentcloud/service_tencentcloud_cbs.go
  website/docs/d/images.html.markdown
Labels: documentation, size/M

#473 `tencentcloud_cdn_domain` fix incorrect setting case crash.
  CHANGELOG.md
  tencentcloud/resource_tc_cdn_domain.go
Labels: size/XS

#472 fix issue: tag not creating in time
  CHANGELOG.md
  tencentcloud/common.go
  tencentcloud/data_source_tc_cfs_file_systems_test.go
  tencentcloud/resource_tc_as_scaling_group.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_ccn.go
  tencentcloud/resource_tc_ccn_test.go
  tencentcloud/resource_tc_cfs_file_system.go
  tencentcloud/resource_tc_cfs_file_system_test.go
  tencentcloud/resource_tc_clb_instance.go
  tencentcloud/resource_tc_clb_instance_test.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/resource_tc_redis_instance_test.go
  tencentcloud/service_tencentcloud_cbs.go
  tencentcloud/service_tencentcloud_clb.go
  website/docs/r/ccn.html.markdown
  website/docs/r/cfs_file_system.html.markdown
Labels: documentation, size/XL

#474 fix: gaap listener destroy may fail
  CHANGELOG.md
  tencentcloud/resource_tc_gaap_http_domain_test.go
  tencentcloud/resource_tc_gaap_layer4_listener_test.go
  tencentcloud/resource_tc_gaap_layer7_listener_test.go
  tencentcloud/service_tencentcloud_gaap.go
Labels: size/M
