Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2020-04, with the labels that each got.

#368 add retry process to resource `tencentcloud_vpc`
  tencentcloud/resource_tc_cam_group.go
  tencentcloud/resource_tc_cam_group_membership.go
  tencentcloud/resource_tc_cam_group_policy_attachment.go
  tencentcloud/resource_tc_cam_policy.go
  tencentcloud/resource_tc_cam_role.go
  tencentcloud/resource_tc_cam_role_policy_attachment.go
  tencentcloud/resource_tc_cam_saml_provider.go
  tencentcloud/resource_tc_cam_user.go
  tencentcloud/resource_tc_cam_user_policy_attachment.go
  tencentcloud/service_tencentcloud_vpc.go
Labels: size/L

#357 support cdn domain
  CHANGELOG.md
  examples/tencentcloud-cdn/main.tf
  examples/tencentcloud-cdn/version.tf
  gendoc/index.go
  gendoc/template.go
  go.sum
  tencentcloud/connectivity/client.go
  tencentcloud/extension_cdn.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_cdn_domain.go
  tencentcloud/resource_tc_cdn_domain_test.go
  tencentcloud/service_tencentcloud_cdn.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdn/v20180606/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdn/v20180606/models.go
  vendor/modules.txt
  website/docs/r/cdn_domain.html.markdown
  website/tencentcloud.erb
Labels: dependencies, documentation, size/XXL

#370 Fix cvm modify password timeout
  tencentcloud/resource_tc_instance.go
Labels: size/XS

#371 fix crash issue
  tencentcloud/data_source_tc_cam_users.go
  tencentcloud/data_source_tc_cam_users_test.go
  tencentcloud/resource_tc_cam_user.go
  website/docs/d/cam_users.html.markdown
Labels: documentation, size/XS

#380 Fix bug when trying to destroy resources containing CVM and key pair
  CHANGELOG.md
  tencentcloud/extension_cvm.go
  tencentcloud/resource_tc_key_pair.go
Labels: size/XS

#383 Optimize mysql(host , ro) and tcaplus(password) resource
  CHANGELOG.md
  tencentcloud/basic_test.go
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_availability_zones.go
  tencentcloud/data_source_tc_cam_policies.go
  tencentcloud/data_source_tc_cfs_access_groups.go
  tencentcloud/data_source_tc_cfs_access_rules.go
  tencentcloud/data_source_tc_cfs_file_systems.go
  tencentcloud/data_source_tc_eip.go
  tencentcloud/data_source_tc_eips.go
  tencentcloud/data_source_tc_image.go
  tencentcloud/data_source_tc_images.go
  tencentcloud/data_source_tc_instance_types.go
  tencentcloud/data_source_tc_instances.go
  tencentcloud/data_source_tc_key_pairs.go
  tencentcloud/data_source_tc_placement_groups.go
  tencentcloud/data_source_tc_reserved_instance_configs.go
  tencentcloud/data_source_tc_reserved_instances.go
  tencentcloud/resource_tc_as_scaling_group.go
  tencentcloud/resource_tc_cbs_snapshot_policy_attachment.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_cfs_access_rule.go
  tencentcloud/resource_tc_cfs_file_system.go
  tencentcloud/resource_tc_container_cluster.go
  tencentcloud/resource_tc_container_cluster_instance.go
  tencentcloud/resource_tc_dayu_cc_https_policy.go
  tencentcloud/resource_tc_dayu_l7_rule.go
  tencentcloud/resource_tc_eip_association.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_key_pair.go
  tencentcloud/resource_tc_kubernetes_as_scaling_group.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_scale_worker.go
  tencentcloud/resource_tc_mysql_account.go
  tencentcloud/resource_tc_mysql_account_privilege.go
  tencentcloud/resource_tc_mysql_account_privilege_test.go
  tencentcloud/resource_tc_mysql_account_test.go
  tencentcloud/resource_tc_mysql_instance.go
  tencentcloud/resource_tc_mysql_privilege.go
  tencentcloud/resource_tc_mysql_privilege_test.go
  tencentcloud/resource_tc_mysql_readonly_instance.go
  tencentcloud/resource_tc_mysql_readonly_instance_test.go
  tencentcloud/resource_tc_placement_group.go
  tencentcloud/resource_tc_reserved_instance.go
  tencentcloud/resource_tc_tcaplus_application.go
  tencentcloud/resource_tc_tcaplus_application_test.go
  tencentcloud/resource_tc_vpn_connection.go
  tencentcloud/service_tencentcloud_monitor.go
  tencentcloud/service_tencentcloud_mysql.go
  tencentcloud/service_tencentcloud_scf.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/monitor/v20180724/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/monitor/v20180724/models.go
  vendor/modules.txt
  website/docs/r/mysql_account.html.markdown
  website/docs/r/mysql_account_privilege.html.markdown
  website/docs/r/mysql_privilege.html.markdown
Labels: dependencies, documentation, size/XXL

#384 cvm support import allocate_public_ip
  CHANGELOG.md
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_instance_test.go
  tencentcloud/service_tencentcloud_vpc.go
Labels: size/XS

#386 fix multi-attachment deletion issue
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/service_tencentcloud_clb.go
Labels: size/XS

#385 vpc & subnets & route types filters
  CHANGELOG.md
  tencentcloud/connectivity/region.go
  tencentcloud/data_source_tc_mysql_zone_config.go
  tencentcloud/data_source_tc_redis_zone_config.go
  tencentcloud/data_source_tc_route_table.go
  tencentcloud/data_source_tc_subnet.go
  tencentcloud/data_source_tc_vpc.go
  tencentcloud/data_source_tc_vpc_instances.go
  tencentcloud/data_source_tc_vpc_instances_test.go
  tencentcloud/data_source_tc_vpc_route_tables.go
  tencentcloud/data_source_tc_vpc_route_tables_test.go
  tencentcloud/data_source_tc_vpc_subnets.go
  tencentcloud/data_source_tc_vpc_subnets_test.go
  tencentcloud/extension_redis.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/resource_tc_subnet.go
  tencentcloud/resource_tc_subnet_test.go
  tencentcloud/resource_tc_vpc.go
  tencentcloud/resource_tc_vpc_test.go
  tencentcloud/service_tencentcloud_vpc.go
  website/docs/d/vpc_instances.html.markdown
  website/docs/d/vpc_route_tables.html.markdown
  website/docs/d/vpc_subnets.html.markdown
  website/docs/r/redis_instance.html.markdown
Labels: documentation, size/XL

#387 fix bugs when trying destroy multi-attachments resources
  CHANGELOG.md
  tencentcloud/resource_tc_cam_group_membership.go
  tencentcloud/resource_tc_clb_attachment.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/service_tencentcloud_cam.go
  website/docs/r/redis_instance.html.markdown
Labels: documentation, size/S

#394 cbs supprot modify tags
  CHANGELOG.md
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_cbs_storage_test.go
Labels: size/XS

#396 cdn domain add argument cname
  CHANGELOG.md
  tencentcloud/resource_tc_cdn_domain.go
  website/docs/r/cdn_domain.html.markdown
Labels: documentation, size/XS

#397 fix cdn domain doc error
  tencentcloud/resource_tc_cdn_domain.go
  website/docs/r/cdn_domain.html.markdown
Labels: documentation, size/XS

#399 cos mark the object as destroyed when the object not exist
  CHANGELOG.md
  tencentcloud/data_source_tc_cos_buckets_test.go
  tencentcloud/resource_tc_cos_bucket_object.go
  tencentcloud/service_tencentcloud_cos.go
Labels: size/XS

#398 tke attachment resource
  CHANGELOG.md
  tencentcloud/provider.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_kubernetes_cluster_attachment.go
  tencentcloud/resource_tc_kubernetes_cluster_attachment_test.go
  tencentcloud/service_tencentcloud_tke.go
  website/docs/r/kubernetes_cluster_attachment.html.markdown
  website/tencentcloud.erb
Labels: documentation, size/XL

#401 resource `tencentcloud_ccn_attachment`add parameter `ccn_uin`
  tencentcloud/data_source_tc_tcaplus_applications.go
  tencentcloud/resource_tc_ccn_attachment.go
  tencentcloud/service_tencentcloud_ccn.go
  website/docs/d/tcaplus_applications.html.markdown
  website/docs/r/ccn_attachment.html.markdown
Labels: documentation, size/L

#402 add attribute `force_delete` with resource `tencentcloud_instance`
  tencentcloud/resource_tc_instance.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/M

#403 fixed scf update zip_file
  CHANGELOG.md
  tencentcloud/data_source_tc_scf_functions_test.go
  tencentcloud/data_source_tc_scf_logs_test.go
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_scf_function.go
  tencentcloud/resource_tc_scf_function_test.go
  website/docs/r/instance.html.markdown
  website/docs/r/scf_function.html.markdown
Labels: documentation, size/XL
