Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2020-03, with the labels that each got.

#342 support TKE-Optimized cluster os.
  CHANGELOG.md
  tencentcloud/extension_tke.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/service_tencentcloud_tke.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  website/docs/r/kubernetes_cluster.html.markdown
Labels: dependencies, documentation, size/XL

#345 Fix key_pair do not work when the end of public_key contains spaces
  CHANGELOG.md
  tencentcloud/resource_tc_key_pair.go
Labels: size/XS

#346 Fix CAM read nil issue
  CHANGELOG.md
  tencentcloud/resource_tc_cam_policy.go
  tencentcloud/resource_tc_cam_role.go
  tencentcloud/resource_tc_cam_saml_provider.go
  tencentcloud/resource_tc_cam_user.go
  tencentcloud/resource_tc_dayu_cc_http_policy.go
Labels: size/S

#347 Add internet and intranet support for kubernetes .
  CHANGELOG.md
  tencentcloud/extension_tke.go
  tencentcloud/resource_tc_kubernetes_cluster.go
  tencentcloud/resource_tc_kubernetes_cluster_test.go
  tencentcloud/service_tencentcloud_tke.go
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/XL

#349 Fix scf trigger does not support cos_region
  CHANGELOG.md
  tencentcloud/data_source_tc_scf_functions.go
  tencentcloud/extension_scf.go
  tencentcloud/resource_tc_scf_function.go
  tencentcloud/resource_tc_scf_function_test.go
  website/docs/r/scf_function.html.markdown
Labels: documentation, size/S

#350 scf support nodejs10.15
  CHANGELOG.md
  tencentcloud/extension_scf.go
  tencentcloud/resource_tc_key_pair.go
  tencentcloud/resource_tc_scf_function.go
  website/docs/r/scf_function.html.markdown
Labels: documentation, size/S

#351 fix scf upload local file error
  CHANGELOG.md
  tencentcloud/resource_tc_scf_function.go
  tencentcloud/service_tencentcloud_scf.go
Labels: size/S

#352 fix scf retry duplicate function error
  tencentcloud/service_tencentcloud_scf.go
Labels: size/XS

#353 fixed delete_with_instance description of instance
  tencentcloud/resource_tc_instance.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#355 replace new api for tcaplus && resource tencentcloud_tcaplus_idl add new attribute zone_id
  CHANGELOG.md
  go.mod
  go.sum
  tencentcloud/data_source_tc_mongodb_zone_config.go
  tencentcloud/data_source_tc_tcaplus_applications.go
  tencentcloud/data_source_tc_tcaplus_idls_test.go
  tencentcloud/data_source_tc_tcaplus_tables.go
  tencentcloud/data_source_tc_tcaplus_tables_test.go
  tencentcloud/data_source_tc_tcaplus_zones.go
  tencentcloud/resource_tc_tcaplus_application.go
  tencentcloud/resource_tc_tcaplus_idl.go
  tencentcloud/resource_tc_tcaplus_idl_test.go
  tencentcloud/resource_tc_tcaplus_table.go
  tencentcloud/resource_tc_tcaplus_table_test.go
  tencentcloud/resource_tc_tcaplus_zone.go
  tencentcloud/service_tencentcloud_tcaplus.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cam/v20190116/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cam/v20190116/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cfs/v20190719/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/client_profile.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dayu/v20180709/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dayu/v20180709/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dc/v20180410/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/mongodb/v20180408/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/scf/v20180416/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/scf/v20180416/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcaplusdb/v20190823/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcaplusdb/v20190823/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/wss/v20180426/models.go
  vendor/modules.txt
  website/docs/r/tcaplus_idl.html.markdown
Labels: dependencies, size/XXL

#356 add new atrribute `delete_force` of resource `tencentcloud_cam_user`
  CHANGELOG.md
  examples/tencentcloud-cam/main.tf
  tencentcloud/data_source_tc_cam_group_memberships_test.go
  tencentcloud/data_source_tc_cam_user_policy_attachments_test.go
  tencentcloud/data_source_tc_cam_users_test.go
  tencentcloud/resource_tc_cam_group.go
  tencentcloud/resource_tc_cam_group_membership.go
  tencentcloud/resource_tc_cam_group_membership_test.go
  tencentcloud/resource_tc_cam_group_policy_attachment.go
  tencentcloud/resource_tc_cam_policy.go
  tencentcloud/resource_tc_cam_role.go
  tencentcloud/resource_tc_cam_role_policy_attachment.go
  tencentcloud/resource_tc_cam_saml_provider.go
  tencentcloud/resource_tc_cam_user.go
  tencentcloud/resource_tc_cam_user_policy_attachment.go
  tencentcloud/resource_tc_cam_user_policy_attachment_test.go
  tencentcloud/resource_tc_cam_user_test.go
  website/docs/r/cam_user.html.markdown
Labels: documentation, size/L

#358 add create nonretryable error
  tencentcloud/resource_tc_cam_group.go
  tencentcloud/resource_tc_cam_policy.go
  tencentcloud/resource_tc_cam_role.go
  tencentcloud/resource_tc_cam_saml_provider.go
  tencentcloud/resource_tc_cam_user.go
Labels: size/S

#359 add time sleep to keep safe read
  tencentcloud/resource_tc_cam_group.go
  tencentcloud/resource_tc_cam_group_membership.go
  tencentcloud/resource_tc_cam_group_policy_attachment.go
  tencentcloud/resource_tc_cam_policy.go
  tencentcloud/resource_tc_cam_role.go
  tencentcloud/resource_tc_cam_role_policy_attachment.go
  tencentcloud/resource_tc_cam_saml_provider.go
  tencentcloud/resource_tc_cam_user.go
  tencentcloud/resource_tc_cam_user_policy_attachment.go
  tencentcloud/service_tencentcloud_cam.go
Labels: size/S

#360 optimize cam user description
  tencentcloud/resource_tc_cam_user.go
  website/docs/r/cam_user.html.markdown
Labels: documentation, size/M

#363 optimize the api style
  tencentcloud/resource_tc_cam_group.go
  tencentcloud/resource_tc_cam_group_membership.go
  tencentcloud/resource_tc_cam_group_policy_attachment.go
  tencentcloud/resource_tc_cam_group_test.go
  tencentcloud/resource_tc_cam_policy.go
  tencentcloud/resource_tc_cam_role.go
  tencentcloud/resource_tc_cam_role_policy_attachment.go
  tencentcloud/resource_tc_cam_saml_provider.go
  tencentcloud/resource_tc_cam_user.go
  tencentcloud/resource_tc_cam_user_policy_attachment.go
Labels: size/M

#364 Fix cbs is not found after creating
  tencentcloud/resource_tc_cbs_storage.go
Labels: size/XS

#365 Data Source tencentcloud_vpc_subnets add new argument vpc_id
  CHANGELOG.md
  tencentcloud/data_source_tc_vpc_subnets.go
  tencentcloud/data_source_tc_vpc_subnets_test.go
  website/docs/d/vpc_subnets.html.markdown
Labels: documentation, size/S

#366 Fill in the missing parameter `zone_id`
  examples/tencentcloud-tcaplus/main.tf
  tencentcloud/resource_tc_tcaplus_idl.go
  tencentcloud/resource_tc_tcaplus_table.go
  website/docs/r/tcaplus_idl.html.markdown
  website/docs/r/tcaplus_table.html.markdown
Labels: documentation, size/XS

#367 update go version of tests
  .travis.yml
  website/docs/r/tcaplus_table.html.markdown
Labels: documentation, size/XS

#369 bug fix : `tencentcloud_kubernetes_as_scaling_group` set a value to argument `key_ids` cause error
  CHANGELOG.md
  tencentcloud/resource_tc_kubernetes_as_scaling_group.go
Labels: size/XS
