Repository tencentcloudstack/terraform-provider-tencentcloud, pull requests merged in 2022-09, with the labels that each got.

#1232 Feat/support teo
  go.mod
  go.sum
  tencentcloud/connectivity/client.go
  tencentcloud/data_source_tc_teo_zone_available_plans.go
  tencentcloud/data_source_tc_teo_zone_ddos_policy.go
  tencentcloud/provider.go
  tencentcloud/resource_tc_mysql_instance.go
  tencentcloud/resource_tc_teo_application_proxy.go
  tencentcloud/resource_tc_teo_application_proxy_rule.go
  tencentcloud/resource_tc_teo_application_proxy_rule_test.go
  tencentcloud/resource_tc_teo_application_proxy_test.go
  tencentcloud/resource_tc_teo_ddos_policy.go
  tencentcloud/resource_tc_teo_ddos_policy_test.go
  tencentcloud/resource_tc_teo_default_certificate.go
  tencentcloud/resource_tc_teo_default_certificate_test.go
  tencentcloud/resource_tc_teo_dns_record.go
  tencentcloud/resource_tc_teo_dns_sec.go
  tencentcloud/resource_tc_teo_dns_sec_test.go
  tencentcloud/resource_tc_teo_host_certificate.go
  tencentcloud/resource_tc_teo_host_certificate_test.go
  tencentcloud/resource_tc_teo_load_balancing.go
  tencentcloud/resource_tc_teo_origin_group.go
  tencentcloud/resource_tc_teo_origin_group_test.go
  tencentcloud/resource_tc_teo_rule_engine.go
  tencentcloud/resource_tc_teo_rule_engine_test.go
  tencentcloud/resource_tc_teo_security_policy.go
  tencentcloud/resource_tc_teo_security_policy_test.go
  tencentcloud/resource_tc_teo_zone.go
  tencentcloud/resource_tc_teo_zone_setting.go
  tencentcloud/resource_tc_teo_zone_setting_test.go
  tencentcloud/resource_tc_teo_zone_test.go
  tencentcloud/service_tencentcloud_teo.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/oidc_role_arn_provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/role_arn_credential.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/LICENSE
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220106/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220106/errors.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/teo/v20220106/models.go
  vendor/modules.txt
  website/docs/d/teo_zone_available_plans.html.markdown
  website/docs/d/teo_zone_ddos_policy.html.markdown
  website/docs/r/teo_application_proxy.html.markdown
  website/docs/r/teo_application_proxy_rule.html.markdown
  website/docs/r/teo_ddos_policy.html.markdown
  website/docs/r/teo_default_certificate.html.markdown
  website/docs/r/teo_dns_record.html.markdown
  website/docs/r/teo_dns_sec.html.markdown
  website/docs/r/teo_host_certificate.html.markdown
  website/docs/r/teo_load_balancing.html.markdown
  website/docs/r/teo_origin_group.html.markdown
  website/docs/r/teo_rule_engine.html.markdown
  website/docs/r/teo_security_policy.html.markdown
  website/docs/r/teo_zone.html.markdown
  website/docs/r/teo_zone_setting.html.markdown
  website/tencentcloud.erb
Labels: run check

#1242 fix sg_rule policy_index not effect
  tencentcloud/resource_tc_security_group_rule.go
  tencentcloud/resource_tc_security_group_rule_test.go
  tencentcloud/service_tencentcloud_vpc.go
Labels: run check

#1240 fix: eip read not support internet_charge_type
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_eip_test.go
Labels: run check

#1237 fix: tke - node pool instype fixed
  tencentcloud/basic_test.go
  tencentcloud/resource_tc_kubernetes_cluster_endpoint_test.go
  tencentcloud/resource_tc_kubernetes_node_pool_test.go
Labels: run check

#1218 fix: redis node upgrade optimize
  tencentcloud/commom_test.go
  tencentcloud/common.go
  tencentcloud/resource_tc_redis_backup_config_test.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/resource_tc_redis_instance_test.go
  tencentcloud/service_tencentcloud_redis.go
  website/docs/r/redis_instance.html.markdown
Labels: run check

#1246 update teo doc
  tencentcloud/provider.go
  website/docs/d/teo_zone_available_plans.html.markdown
  website/docs/d/teo_zone_ddos_policy.html.markdown
  website/docs/r/tem_app_config.html.markdown
  website/docs/r/tem_application.html.markdown
  website/docs/r/tem_environment.html.markdown
  website/docs/r/tem_gateway.html.markdown
  website/docs/r/tem_log_config.html.markdown
  website/docs/r/tem_scale_rule.html.markdown
  website/docs/r/tem_workload.html.markdown
  website/docs/r/teo_application_proxy.html.markdown
  website/docs/r/teo_application_proxy_rule.html.markdown
  website/docs/r/teo_ddos_policy.html.markdown
  website/docs/r/teo_default_certificate.html.markdown
  website/docs/r/teo_dns_record.html.markdown
  website/docs/r/teo_dns_sec.html.markdown
  website/docs/r/teo_host_certificate.html.markdown
  website/docs/r/teo_load_balancing.html.markdown
  website/docs/r/teo_origin_group.html.markdown
  website/docs/r/teo_rule_engine.html.markdown
  website/docs/r/teo_security_policy.html.markdown
  website/docs/r/teo_zone.html.markdown
  website/docs/r/teo_zone_setting.html.markdown
  website/tencentcloud.erb
Labels: run check

#1238 fix: cynosdb param_items not effect in create cluster
  go.mod
  go.sum
  tencentcloud/extension_cynosdb.go
  tencentcloud/resource_tc_cynosdb_cluster.go
  tencentcloud/resource_tc_cynosdb_cluster_test.go
  tencentcloud/service_tencentcloud_cynosdb.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cynosdb/v20190107/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cynosdb/v20190107/errors.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cynosdb/v20190107/models.go
  vendor/modules.txt
  website/docs/r/cynosdb_cluster.html.markdown
Labels: run check

#1241 fix: update irregular type
  tencentcloud/resource_tc_monitor_tmp_tke_cluster_agent.go
  tencentcloud/resource_tc_monitor_tmp_tke_global_notification.go
  tencentcloud/resource_tc_monitor_tmp_tke_global_notification_test.go
  website/docs/r/monitor_tmp_tke_cluster_agent.html.markdown
  website/docs/r/monitor_tmp_tke_global_notification.html.markdown
Labels: run check

#1250 feat: pr lable
  .github/labeler-pr-triage.yml
  .github/workflows/pr_label.yml
Labels: github_actions

#1247 feat: add datasource for cynosdb spec
  go.sum
  tencentcloud/data_source_tc_cynosdb_zone_config.go
  tencentcloud/data_source_tc_cynosdb_zone_config_test.go
  tencentcloud/provider.go
  tencentcloud/service_tencentcloud_cynosdb.go
  website/docs/d/cynosdb_zone_config.html.markdown
  website/tencentcloud.erb
Labels: run check, tests, service, doc, trigger_label_event

#1253 system support bssd
  tencentcloud/extension_cvm.go
  tencentcloud/resource_tc_instance.go
  website/docs/r/instance.html.markdown
Labels: doc, resource, extension

#1195 Fix/nodepool disk encrypt
  go.mod
  go.sum
  tencentcloud/basic_test.go
  tencentcloud/resource_tc_kubernetes_cluster_endpoint_test.go
  tencentcloud/resource_tc_kubernetes_node_pool.go
  tencentcloud/resource_tc_kubernetes_node_pool_test.go
  tencentcloud/service_tencentcloud_tke.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/errors.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go
  vendor/modules.txt
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: run check

#1260 feat: dnspod record import
  tencentcloud/resource_tc_dnspod_record.go
  tencentcloud/resource_tc_dnspod_record_test.go
  website/docs/r/dnspod_record.html.markdown
Labels: run check

#1261 Fix/cluster agent status handle
  tencentcloud/basic_test.go
  tencentcloud/resource_tc_monitor_tmp_exporter_integration_test.go
  tencentcloud/resource_tc_monitor_tmp_instance.go
  tencentcloud/resource_tc_monitor_tmp_tke_cluster_agent_test.go
Labels: run check

#1263 fix: tcaplusdb support tdr
  examples/tencentcloud-persistent-resource/tcaplus.tf
  tencentcloud/basic_test.go
  tencentcloud/resource_tc_tcaplus_idl.go
  tencentcloud/resource_tc_tcaplus_idl_test.go
Labels: run check

#1264 update tem application
  tencentcloud/resource_tc_tem_application.go
  website/docs/r/tem_application.html.markdown
Labels: run check

#1265 fix: update cvm unit test image
  tencentcloud/resource_tc_instance_test.go
Labels: run check

#1266 adjust the account type to common for the cos_bucket_domain_certificate_attachment_test
  tencentcloud/basic_test.go
  tencentcloud/resource_tc_cos_bucket_domain_certificate_attachment_test.go
Labels: run check

#1270 fix: cvm - process launch failed and empty read result
  tencentcloud/resource_tc_instance.go
Labels: run check

#1272 fix: cos resource context conflict
  tencentcloud/data_source_tc_cos_buckets_test.go
  tencentcloud/resource_tc_cos_bucket_domain_certificate_attachment_test.go
  tencentcloud/service_tencentcloud_cos.go
Labels: run check

#1273 fix: cam_sso - Add oidc sweeper
  tencentcloud/resource_tc_cam_role_sso_test.go
Labels: run check

#1274 Fix/redis basic testcase
  tencentcloud/data_source_tc_redis_instances_test.go
  tencentcloud/resource_tc_redis_backup_config_test.go
  tencentcloud/resource_tc_redis_instance.go
  tencentcloud/resource_tc_redis_instance_test.go
  website/docs/r/redis_instance.html.markdown
Labels: run check

#1275 support cam policy with restrict tag
  go.mod
  go.sum
  tencentcloud/resource_tc_cbs_snapshot.go
  tencentcloud/resource_tc_cbs_storage.go
  tencentcloud/resource_tc_eip.go
  tencentcloud/resource_tc_eni.go
  tencentcloud/resource_tc_image.go
  tencentcloud/resource_tc_key_pair.go
  tencentcloud/resource_tc_nat_gateway.go
  tencentcloud/resource_tc_route_table.go
  tencentcloud/resource_tc_security_group.go
  tencentcloud/resource_tc_subnet.go
  tencentcloud/resource_tc_vpc_acl.go
  tencentcloud/service_tencentcloud_cbs.go
  tencentcloud/service_tencentcloud_vpc.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/errors.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/models.go
  vendor/modules.txt
  website/docs/r/cbs_snapshot.html.markdown
  website/docs/r/image.html.markdown
  website/docs/r/key_pair.html.markdown
  website/docs/r/vpc_acl.html.markdown
Labels: trigger_label_event

#1276 catch exception when eip nil
  tencentcloud/resource_tc_eip.go
Labels: run check

#1277 fix: redis - testcase network
  tencentcloud/data_source_tc_redis_instances_test.go
  tencentcloud/resource_tc_redis_backup_config_test.go
  tencentcloud/resource_tc_redis_instance_test.go
Labels: run check

#1284 fix: tke - endpoint new sg ingress avoid to diff hidden default rule
  tencentcloud/resource_tc_kubernetes_cluster_endpoint_test.go
Labels: run check

#1285 feat: cvm - support multiple key_ids, deprecate key_name
  tencentcloud/resource_tc_instance.go
  tencentcloud/resource_tc_instance_test.go
  tencentcloud/resource_tc_key_pair.go
  tencentcloud/service_tencentcloud_cvm.go
  website/docs/r/instance.html.markdown
Labels: run check

#1282 supprot the white/black IP list for es
  tencentcloud/resource_tc_elasticsearch_instance.go
  tencentcloud/resource_tc_elasticsearch_instance_test.go
  tencentcloud/service_tencentcloud_elasticsearch.go
  website/docs/r/elasticsearch_instance.html.markdown
Labels: run check

#1291 Feat/tcr vpc attach
  go.mod
  go.sum
  tencentcloud/resource_tc_tcr_vpc_attachment.go
  tencentcloud/service_tencentcloud_tcr.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/errors.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/models.go
  vendor/modules.txt
  website/docs/r/tcr_vpc_attachment.html.markdown
Labels: run check

#1289 feat: tcr - support replications
  go.mod
  go.sum
  tencentcloud/resource_tc_tcr_instance.go
  tencentcloud/resource_tc_tcr_instance_test.go
  tencentcloud/service_tencentcloud_tcr.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/modules.txt
  website/docs/r/tcr_instance.html.markdown
Labels: run check

#1290 support force clean for cos bucket
  tencentcloud/resource_tc_cos_bucket.go
  tencentcloud/resource_tc_cos_bucket_test.go
  tencentcloud/service_tencentcloud_cos.go
  website/docs/r/cos_bucket.html.markdown
Labels: run check

#1292 fix: tcr - add replica retry duration
  tencentcloud/resource_tc_tcr_instance.go
  tencentcloud/service_tencentcloud_tcr.go
Labels: run check

#1295 fix: add agent_id
  tencentcloud/resource_tc_monitor_tmp_cvm_agent.go
  website/docs/r/monitor_tmp_cvm_agent.html.markdown
Labels: run check

#1297 fix: maintenance doc
  tencentcloud/resource_tc_monitor_tmp_alert_rule.go
  website/docs/r/monitor_tmp_alert_rule.html.markdown
Labels: run check

#1296 fix: tke - nodepool and endpoint security group
  tencentcloud/resource_tc_kubernetes_cluster_endpoint_test.go
  tencentcloud/resource_tc_kubernetes_node_pool_test.go
Labels: run check

#1293 Fix/security group rule
  tencentcloud/resource_tc_security_group_rule.go
  tencentcloud/resource_tc_security_group_rule_test.go
  tencentcloud/service_tencentcloud_vpc.go
  website/docs/r/security_group_rule.html.markdown
Labels: run check
